<!-- {"title": "The ten detectors", "order": 40, "sources": ["README.md", "docs/reports/2026-09-26_worked-examples.md"], "lead": "Ten detectors run on every file, all behind one contract: a score in [0, 1] that rises with synthetic likelihood, one plain-English sentence of evidence, named features, and a status. Three vote, one may only lower the score, one gates, five are evidence and routing. Each card names the sponsor's rubric technique it implements, what it measures, its role, its numbers and one real sentence it wrote about a test file.", "description": "HEARSAY's ten detectors mapped to the NSA rubric: technique, role, what each measures, its numbers and a real evidence sentence."} -->
<h2 id="rubric">The rubric, mapped</h2>
<p>The sponsor awards diversity points for each distinct technique a system actually uses, plus a bonus for choosing analyses per file. {{src:README.md#the-eight-forensic-techniques|Source: the README's technique table.}}</p>
<div class="table-wrap"><table>
<thead><tr><th>Rubric technique</th><th>Detector</th><th>How it is used</th></tr></thead>
<tbody>
<tr><td>Container, digital file forensics and metadata</td><td><a href="#container">container</a></td><td>routing</td></tr>
<tr><td>Spectral / frequency-domain analysis</td><td><a href="#handcrafted">handcrafted</a>, <a href="#spectra">Spectra-AASIST</a></td><td>fused ({{num:20%|README.md#the-eight-forensic-techniques}}); suppressor</td></tr>
<tr><td>Prosody and phonetics</td><td><a href="#handcrafted">handcrafted</a></td><td>fused</td></tr>
<tr><td>Acoustic-environment consistency (ENF)</td><td><a href="#enf">enf</a></td><td>evidence</td></tr>
<tr><td>Compression forensics</td><td><a href="#compression">compression</a></td><td>evidence</td></tr>
<tr><td>Speaker-embedding consistency</td><td><a href="#drift">speaker_drift</a></td><td>evidence</td></tr>
<tr><td>Deep-learning anti-spoofing</td><td><a href="#m1b">M1b</a>, <a href="#m5">M5</a>, <a href="#spectra">Spectra-AASIST</a></td><td>fused (Spectra as suppressor only)</td></tr>
<tr><td>Splice / discontinuity detection</td><td><a href="#splice">splice</a></td><td>evidence</td></tr>
<tr><td>Agentic orchestration bonus</td><td>the <a href="how-it-decides.html#router">router</a> and the <a href="#gate">speech gate</a></td><td>rules over measured facts, a routing log per file, and a measured router-on-versus-off ablation</td></tr>
</tbody></table></div>
<h2 id="fused">The three that vote</h2>
<ul class="cards">
<li class="card" id="m1b"><span class="role fused">fused · weight {{num:0.6|README.md#how-it-decides}}</span><h3>M1b: frozen XLS-R with a logistic probe</h3><p><strong>Technique:</strong> deep-learning anti-spoofing. <strong>What it measures:</strong> the hidden state of layer 7 of {{term:XLS-R}} (frozen), averaged over time, then a class-balanced logistic regression and a {{term:Platt map}}. M1b adds 40 VCTK real speakers from {{term:ASVspoof 2019}} and a spoof anchor to the training folds only. Layer 7 won inner cross-validation; mid-depth layers carry the acoustic detail that separates vocoders, the top layers are tuned for phonetic content.</p>
<p><strong>Numbers:</strong> inner {{num:0.301|README.md#numbers}}, holdout {{num:0.072|README.md#numbers}} (EER {{num:1.4%|README.md#numbers}}), In-the-Wild {{num:0.342|README.md#numbers}} (the results table rounds it {{num:0.343|README.md#results-at-a-glance}}), In-the-Wild false alarms {{num:0.8%|README.md#numbers}}, test share above {{num:0.5|README.md#numbers}} {{num:26.8%|README.md#numbers}}.</p>
<pre class="evidence-line">XLS-R layer-7 probe: calibrated log-likelihood ratio -5.78 (real-like, P=0.00)</pre>
<p class="src-note">{{src:README.md#how-it-decides|Sentence from the README's trace of HGT1046947.wav.}} Spec: <a href="specs/xlsr-probe.html">the XLS-R probe</a>.</p></li>
<li class="card" id="handcrafted"><span class="role fused">fused · weight {{num:0.2|README.md#how-it-decides}}</span><h3>Handcrafted spectral and prosody features</h3><p><strong>Techniques:</strong> spectral analysis and prosody. <strong>What it measures:</strong> {{num:234|README.md#the-eight-forensic-techniques}} features: spectral contrast, flatness, flux, roll-off, MFCC, LFCC and CQCC statistics, group-delay and phase-coherence cues; YIN pitch spread and slope, jitter and shimmer, loudness modulation, pauses, breath frames; {{term:gradient-boosted trees}} evaluated in numpy. Pitch variability is the one prosody cue that carried signal. The shipped version (v5b) is trained with augmented twins and validated on clean rows only.</p>
<p><strong>Numbers:</strong> inner {{num:0.469|README.md#numbers}}, holdout {{num:0.137|README.md#numbers}} (EER {{num:3.1%|README.md#numbers}}), In-the-Wild false alarms {{num:0.40%|README.md#numbers}}, test share above {{num:0.5|README.md#numbers}} {{num:45.1%|README.md#numbers}}. On its own it is blind to web-sourced fakes; that is why it gets a fifth of the vote, not half.</p>
<pre class="evidence-line">spectral/prosody features real-like (P=0.16): LFCC 16 frame-to-frame change 3.0 SD below real speech (toward synthetic); spectral contrast, band 0 0.8 SD above real speech (toward real); LFCC 1 variability 1.1 SD below real speech (toward real)</pre>
<p class="src-note">{{src:docs/reports/2026-09-26_worked-examples.md#4-hgt1046947wav-the-deep-detectors-disagree-drift-flagged-p--0003-z-mean-0686|Sentence from worked example 4.}} Spec: <a href="specs/handcrafted.html">handcrafted features</a>.</p></li>
<li class="card" id="m5"><span class="role fused">fused · weight {{num:0.2|README.md#how-it-decides}}</span><h3>M5: a trained head on XLS-R</h3><p><strong>Technique:</strong> deep-learning anti-spoofing. <strong>What it measures:</strong> the first 12 layers of XLS-R with learned layer weights, attentive statistics pooling and a linear head, trained on rented A100s with class-blind augmentation (noise, telephony band-limits, reverb, codecs, RawBoost). It did not clear its gate as a replacement for the probe, but it is wrong on different files, and as a third rank input it passed the second pre-declared sweep.</p>
<p><strong>Numbers:</strong> inner {{num:0.302|README.md#numbers}}, holdout {{num:0.363|README.md#numbers}} (EER {{num:6.0%|README.md#numbers}}), In-the-Wild false alarms {{num:0.45%|README.md#numbers}}, test share above {{num:0.5|README.md#numbers}} {{num:25.8%|README.md#numbers}}.</p>
<pre class="evidence-line">XLS-R fine-tuned head (M5, 12 layers, attentive pooling): logit +5.64 (synthetic-like, P=1.00)</pre>
<p class="src-note">{{src:README.md#how-it-decides|Sentence from the README's trace.}} Spec: <a href="specs/m5-head.html">the M5 head</a>.</p></li>
</ul>
<h2 id="suppressor">The one that may only lower a score</h2>
<ul class="cards">
<li class="card" id="spectra"><span class="role">suppressor · weight 0</span><h3>Spectra-AASIST (M3)</h3><p><strong>Techniques:</strong> deep-learning anti-spoofing, spectral. <strong>What it measures:</strong> an off-the-shelf anti-spoofing model (its own XLS-R plus a graph-attention back end), run with no training through the same band-matched input path and crops; short clips are zero-padded to one window. Output: a spoof-minus-bonafide margin. <strong>Role:</strong> if the margin is below −3 and the fused rank is above {{num:0.5|scripts/fuse_sweep.py#L172}}, the rank is halved. It can never raise a score.</p>
<p><strong>Numbers, all possibly in-sample</strong> because its model card names no training set: inner {{num:0.0045|README.md#numbers}}, holdout {{num:0.012|README.md#numbers}} (EER {{num:0.16%|README.md#numbers}}), In-the-Wild {{num:0.065|README.md#numbers}} (its authors evaluated on that set), In-the-Wild false alarms {{num:0.0%|README.md#numbers}}, test share above {{num:0.5|README.md#numbers}} {{num:29.3%|README.md#numbers}}. The leakage probes support the suppressor role: the most perturbation-stable detector, the lowest miss rate on unseen generators, and a step that never raised the fused cost.</p>
<pre class="evidence-line">Spectra-AASIST: spoof-minus-bonafide margin +9.50 (synthetic-like, P=1.00)</pre>
<p class="src-note">{{src:README.md#how-it-decides|Sentence from the README's trace.}} Spec: <a href="specs/spectra-aasist.html">Spectra-AASIST</a>.</p></li>
</ul>
<h2 id="evidence">Evidence and routing, never scored</h2>
<ul class="cards">
<li class="card" id="compression"><span class="role evidence">evidence</span><h3>Compression forensics</h3><p><strong>Technique:</strong> compression forensics. <strong>What it measures:</strong> {{num:19|README.md#the-eight-forensic-techniques}} codec-trace features in 3–7 kHz (spectral holes, floor depth, effective bandwidth), trained with both classes laundered through MP3/AAC so it cannot learn "MP3 = fake". It detects codec history well and the class barely, because the test set reads as laundered throughout. Its effective-bandwidth reading is a routing fact.</p>
<p><strong>Numbers:</strong> inner {{num:0.931|README.md#numbers}}, holdout {{num:0.900|README.md#numbers}} (EER {{num:20.1%|README.md#numbers}}), test share above {{num:0.5|README.md#numbers}} {{num:80.7%|README.md#numbers}}.</p>
<pre class="evidence-line">compression-trace features synthetic-like (P=0.97): whole-clip floor depth 1.7 SD below real speech (toward synthetic); 3-7 kHz valley depth 0.7 SD below real speech (toward synthetic); deep-hole flicker frame to frame 1.7 SD above real speech (toward synthetic)</pre>
<p class="src-note">{{src:docs/reports/2026-09-26_worked-examples.md#1-hgt1013455wav-confident-real-p--0002|Sentence from worked example 1, a confident real file.}} Spec: <a href="specs/compression.html">compression forensics</a>.</p></li>
<li class="card" id="container"><span class="role">routing</span><h3>Container and metadata</h3><p><strong>Technique:</strong> container, file forensics and metadata. <strong>What it measures:</strong> header facts (codec, rate, bit depth, encoder tag). Rule-based on purpose: on our training data the container <em>is</em> the label, and every test file carries the same FFmpeg tag, so it returns a constant score and routes compression forensics. It never reads filenames or filesystem timestamps, because git, zip and Docker rewrite them.</p>
<p><strong>Numbers:</strong> none by design (a constant {{num:0.5|README.md#what-did-not-work}} on this test set).</p>
<pre class="evidence-line">wav/pcm_s16le 16000 Hz mono 16-bit, 1 tag(s) [encoder=Lavf58.29.100]: no class evidence in the container; written by FFmpeg (libavformat), so the file was re-muxed or transcoded at least once</pre>
<p class="src-note">{{src:docs/reports/2026-09-26_worked-examples.md#worked-examples-eight-real-test-files-through-the-shipped-pipeline|The sentence every one of the eight files received.}} Spec: <a href="specs/container.html">container</a>.</p></li>
<li class="card" id="enf"><span class="role evidence">evidence</span><h3>ENF: mains hum</h3><p><strong>Technique:</strong> acoustic-environment consistency. <strong>What it measures:</strong> a 50 or 60 Hz hum and its stability on short windows. Rule-based and mild on purpose: stable hum is in a third of LJ Speech clips and almost no generated audio, so a learned version would learn "hum = real".</p>
<p><strong>Numbers:</strong> flags {{num:24|README.md#what-did-not-work}} test files; never moves a score.</p>
<pre class="evidence-line">no mains hum at 50 or 60 Hz (best 60 Hz candidate: median SNR 2.8 dB, above 12 dB in 0% of frames): no environment evidence either way</pre>
<pre class="evidence-line">enf: mains hum present, stable (recording-environment evidence)</pre>
<p class="src-note">{{src:docs/reports/2026-09-26_worked-examples.md#1-hgt1013455wav-confident-real-p--0002|First sentence from worked example 1;}} {{src:docs/reports/2026-09-26_worked-examples.md#5-hgt3237868wav-a-fake-with-a-stable-mains-hum-p--0935|the routing-log line from example 5, a fake with a stable hum.}} Spec: <a href="specs/enf.html">ENF</a>.</p></li>
<li class="card" id="splice"><span class="role evidence">evidence</span><h3>Splice and discontinuities</h3><p><strong>Technique:</strong> splice / discontinuity detection. <strong>What it measures:</strong> sample-level clicks and DC-offset jumps between {{num:100 ms|README.md#the-eight-forensic-techniques}} windows. On this data it finds vocoder artifacts more than edits, and the sponsor said no test clip is partially synthetic, so it is evidence.</p>
<p><strong>Numbers:</strong> flags {{num:58|README.md#what-did-not-work}} test files; never moves a score.</p>
<pre class="evidence-line">editing seam at 1.59 s: 1 click(s) (largest step 17x the surrounding waveform); consistent with a cut or inserted segment (background-floor range 26 dB, informational)</pre>
<p class="src-note">{{src:docs/reports/2026-09-26_worked-examples.md#8-hgt2305393wav-genuinely-uncertain-and-it-says-so-p--0471-z-mean-0995|Sentence from worked example 8.}} Spec: <a href="specs/splice.html">splice</a>.</p></li>
<li class="card" id="drift"><span class="role evidence">evidence</span><h3>Speaker drift</h3><p><strong>Technique:</strong> speaker-embedding consistency. <strong>What it measures:</strong> {{term:ECAPA}} embeddings on one-second windows; flags a voice that changes within the clip. The finding that keeps it out of the score: fakes are the <em>most</em> self-consistent voices, so fused it would push hard real recordings toward synthetic.</p>
<p><strong>Numbers:</strong> the mean window-to-window similarity separates classes toward fake at AUC {{num:0.73|README.md#what-did-not-work}}; drift flags {{num:16%|README.md#what-did-not-work}} of test files.</p>
<pre class="evidence-line">voice drifts across the clip: minimum window-to-window speaker similarity -0.10 over 14 windows</pre>
<p class="src-note">{{src:README.md#how-it-decides|Sentence from the README's trace.}} Spec: <a href="specs/speaker-drift.html">speaker drift</a>.</p></li>
</ul>
<h2 id="gate-section">The gate</h2>
<ul class="cards">
<li class="card" id="gate"><span class="role">gate</span><h3>Speech gate</h3><p><strong>Part of the orchestration.</strong> <strong>What it measures:</strong> whether a file contains speech at all, from five cues: not silent, at least {{num:5%|README.md#the-eight-forensic-techniques}} voiced, pitch moving, loudness moving, not spectrally flat. Each threshold was set beyond the extreme value in the full test set, so it only catches silence, tones, static and noise; a file that fails skips fusion and goes to the {{term:pinned block}}.</p>
<p><strong>Numbers:</strong> gates {{num:0 of 1,671|README.md#the-eight-forensic-techniques}} test files.</p>
<pre class="evidence-line">speech present: voiced 28% of frames, pitch spread 0.34, loudness std 18.5 dB</pre>
<p class="src-note">{{src:README.md#how-it-decides|Sentence from the README's trace.}} Spec: <a href="specs/speech-gate-policy.html">the speech gate and the default-answer policy</a>.</p></li>
</ul>
<h2 id="numbers-table">All ten in one table</h2>
<p>Normalized minDCF unless marked; "inner" is pooled out-of-fold over the inner rows; "ITW FA" is the In-the-Wild real-speech false-alarm rate at the model's own inner-fold threshold; "test &gt; {{num:0.5|README.md#numbers}}" is a sanity check, not a score. {{src:README.md#numbers|Source: the README's Numbers section.}}</p>
<div class="table-wrap"><table>
<thead><tr><th>Detector</th><th>Role</th><th>Inner</th><th>Holdout</th><th>Holdout EER</th><th>ITW</th><th>ITW FA</th><th>Test &gt; {{num:0.5|README.md#numbers}}</th></tr></thead>
<tbody>
<tr><td>M1b v3</td><td>fused {{num:0.6|README.md#how-it-decides}}</td><td>{{num:0.301|README.md#numbers}}</td><td>{{num:0.072|README.md#numbers}}</td><td>{{num:1.4%|README.md#numbers}}</td><td>{{num:0.342|README.md#numbers}}</td><td>{{num:0.8%|README.md#numbers}}</td><td>{{num:26.8%|README.md#numbers}}</td></tr>
<tr><td>Handcrafted v5b</td><td>fused {{num:0.2|README.md#how-it-decides}}</td><td>{{num:0.469|README.md#numbers}}</td><td>{{num:0.137|README.md#numbers}}</td><td>{{num:3.1%|README.md#numbers}}</td><td>—</td><td>{{num:0.40%|README.md#numbers}}</td><td>{{num:45.1%|README.md#numbers}}</td></tr>
<tr><td>M5 head</td><td>fused {{num:0.2|README.md#how-it-decides}}</td><td>{{num:0.302|README.md#numbers}}</td><td>{{num:0.363|README.md#numbers}}</td><td>{{num:6.0%|README.md#numbers}}</td><td>—</td><td>{{num:0.45%|README.md#numbers}}</td><td>{{num:25.8%|README.md#numbers}}</td></tr>
<tr><td>Spectra-AASIST (possibly in-sample)</td><td>suppressor</td><td>{{num:0.0045|README.md#numbers}}</td><td>{{num:0.012|README.md#numbers}}</td><td>{{num:0.16%|README.md#numbers}}</td><td>{{num:0.065|README.md#numbers}}</td><td>{{num:0.0%|README.md#numbers}}</td><td>{{num:29.3%|README.md#numbers}}</td></tr>
<tr><td>Compression</td><td>evidence</td><td>{{num:0.931|README.md#numbers}}</td><td>{{num:0.900|README.md#numbers}}</td><td>{{num:20.1%|README.md#numbers}}</td><td>—</td><td>—</td><td>{{num:80.7%|README.md#numbers}}</td></tr>
<tr><td>Container, ENF, splice (rule-based)</td><td>routing, evidence</td><td>{{num:1.0|README.md#numbers}}</td><td>{{num:1.0|README.md#numbers}}</td><td>—</td><td>—</td><td>—</td><td>—</td></tr>
<tr><td>Speaker drift</td><td>evidence</td><td colspan="6">not scored as a class detector; see the card above</td></tr>
<tr><td>Speech gate</td><td>gate</td><td colspan="6">no score; gates {{num:0 of 1,671|README.md#the-eight-forensic-techniques}} test files</td></tr>
</tbody></table></div>
