<!-- {"title": "The metric and the default answer", "heading": "The metric, and what to answer when you cannot tell", "order": 20, "sources": ["README.md", "CLAUDE.md", "src/hearsay/metrics.py", "docs/consults/2026-09-26_fusion-strategy_RESPONSE.md", "docs/reports/2026-09-26_fusion-sweep-predeclared.md"], "lead": "Sixty percent of the grade is one number: the normalized minimum detection cost on the sponsor's test set. Under it, calling a real recording synthetic costs about nine times as much as letting a fake through, and only the order of our scores matters. Those two facts explain most of what this system does, including where it puts the files it cannot judge.", "description": "What minDCF is, why a false alarm costs 9.33 misses, why only ranking matters, why the operating threshold sits near 0.9, and why undecidable files are pinned to the real end under both readings of the score."} -->
{{cost-panel}}
<h2 id="explore">Try it</h2>
{{cost-explorer}}
<h2 id="where-it-comes-from">Where the weights come from</h2>
<p>The sponsor's instructions set the analyst's scenario: a {{term:false alarm}} (a real recording flagged as synthetic) costs {{num:4×|CLAUDE.md#conventions}} a {{term:miss}}, and about {{num:70%|CLAUDE.md#conventions}} of the test files are real. Our metric module encodes exactly that: {{src:src/hearsay/metrics.py#L29|C_FA = 4, C_miss = 1, π_synth = 0.3}}, and the normalized cost is {{src:CLAUDE.md#conventions|9.33·P_FA + P_miss}}. The scorer sweeps every threshold and keeps the smallest cost, so the number is the best the ranking could do with a perfect threshold.</p>
{{diagram:cost|The two ways to be wrong: a real file above the threshold is a false alarm and counts 9.33; a synthetic file below it is a miss and counts 1.}}
<h2 id="ranking">Why only ranking matters</h2>
<p>Because the scorer chooses the threshold, any monotone rescaling of our scores changes nothing: a {{term:Platt map}}, a z-score, or the cut at {{num:0.5|README.md#validation}} all leave {{term:minDCF}} exactly where it was. That is why fusion works in ranks, why the {{term:test share}} above {{num:0.5|README.md#validation}} is a smoke alarm and never a selection signal, and why every rule was chosen on minDCF with {{term:EER}} only reported. {{src:README.md#validation|Source: the README's validation section.}}</p>
<h2 id="threshold">Why the operating threshold sits far above the midpoint</h2>
<p>With a false alarm that expensive, calling a file synthetic only pays when the evidence is strong. On a calibrated probability scale the {{term:Bayes threshold}} sits near {{num:0.903|docs/consults/2026-09-26_fusion-strategy_RESPONSE.md#what-to-ignore-and-why}} under the brief's cost, not at {{num:0.5|docs/consults/2026-09-26_fusion-strategy_RESPONSE.md#what-to-ignore-and-why}}. That figure is the cut on a prior-neutral likelihood ratio read as a probability. The probability the TSV carries already includes the prior, and its Bayes cut is {{num:0.8|src/hearsay/metrics.py#L69}}; our metric module's decision logit subtracts the cost term as well, so on it a fixed {{num:50%|src/hearsay/metrics.py#L69}} cut is the Bayes decision. Every intuition anchored on "above {{num:0.5|docs/consults/2026-09-26_fusion-strategy_RESPONSE.md#what-to-ignore-and-why}} means fake" is off by an order of magnitude in likelihood ratio. This is also why the share of test files above {{num:0.5|README.md#validation}} sitting near the stated prior is reassuring but not a score.</p>
<h2 id="two-readings">Two readings of the same score</h2>
<p>The instructions say {{num:1.0|README.md#the-fusion-rule}} = synthetic. The sponsor's shipped scoring code (ASVspoof5's) treats a higher score as bona fide, the opposite. We follow the instructions and never flip; every model logs its cost under the sponsor's code both ways, and a pre-flipped twin of the draft TSV exists in case NSA's feedback shows they grade inverted. {{src:README.md#the-fusion-rule|Source: "Score direction" in the README.}} The second reading also moves the heavy weight: the sponsor code's cost is {{src:docs/reports/2026-09-26_fusion-sweep-predeclared.md#readouts-for-every-candidate|P_FA + 4·P_miss at π 0.5}}, with the 4× on a missed fake. So every readout on this site names its cost: the brief's, or the sponsor code's.</p>
<div class="table-wrap"><table>
<thead><tr><th>Shipped rule</th><th>In-the-Wild, brief cost ({{src:CLAUDE.md#conventions|9.33·P_FA + P_miss}})</th><th>In-the-Wild, sponsor-code cost ({{src:docs/reports/2026-09-26_fusion-sweep-predeclared.md#readouts-for-every-candidate|P_FA + 4·P_miss}})</th></tr></thead>
<tbody><tr><td>{{src:README.md#numbers|A3 w 0.2 + E}}</td><td>{{num:0.228|README.md#numbers}}</td><td>{{num:0.239|README.md#numbers}}</td></tr></tbody>
</table></div>
<h2 id="default-answer">The default answer: the pinned block</h2>
<p>The brief warns that real clips may be perturbed, that fakes are laundered, and that a naive detector will be fooled. It leaves one question to the team: what do you answer when you cannot tell? Silence, music, static, a file that fails to decode. Our first deep probe scored pure silence at {{num:0.99|README.md#orchestration-what-routing-changes}} synthetic, which under this cost would be the most expensive possible mistake if the file were real.</p>
<p>The answer is placement, not a value. Every file we could judge gets a score in [{{num:0.001|README.md#orchestration-what-routing-changes}}, 1]. Undecidable files get scores in [0, {{num:0.001|README.md#orchestration-what-routing-changes}}): strictly below all of them, at the real end, ordered inside the block by the weak M1b signal plus a hash of the filename so no two share a value, with decode failures at the very bottom. {{src:README.md#orchestration-what-routing-changes|Source: "The abstention path".}}</p>
{{diagram:score-line|The score line: synthetic at the top, every judged file in [0.001, 1], the pinned block below 0.001 at the real end.}}
<h3 id="both-readings">Right under both readings of the score</h3>
<p>The block is the one hedge that does not depend on which way NSA's code reads our scores. Let q be the fraction of truly synthetic files inside the block. Placing the block at the bottom is optimal under the brief's cost when q is below {{num:80%|README.md#orchestration-what-routing-changes}}, and under the scoring code's inverted cost when q is above {{num:9.7%|README.md#orchestration-what-routing-changes}}. Undecidable files should sit near the {{num:30%|README.md#orchestration-what-routing-changes}} base rate, which leaves roughly a 3× margin on each side. {{src:docs/consults/2026-09-26_fusion-strategy_RESPONSE.md#what-to-do-adopted|Source: consult item 5.}}</p>
<div class="table-wrap"><table>
<thead><tr><th>Reading of the score</th><th>Where the expensive error sits</th><th>Bottom placement is optimal when</th><th>Expected q for undecidable files</th></tr></thead>
<tbody>
<tr><td>The brief ({{num:1.0|README.md#the-fusion-rule}} = synthetic, false alarm ×4)</td><td>a real file ranked high</td><td>q &lt; {{num:80%|README.md#orchestration-what-routing-changes}}</td><td rowspan="2">near the {{num:30%|README.md#orchestration-what-routing-changes}} prior</td></tr>
<tr><td>The sponsor's code (higher = bona fide, missed fake ×4)</td><td>a fake file ranked high</td><td>q &gt; {{num:9.7%|README.md#orchestration-what-routing-changes}}</td></tr>
</tbody></table></div>
<p>No test file is gated today, so the block costs nothing on the current ranking. It only protects against a silent or musical file being scored as synthetic, which our deep models do on their own.</p>
<h2 id="decoding">Reading the draft review</h2>
<p>NSA scored one early submission per team. We sent the exact artifact we ship and decided in advance what each returned number would mean. NSA returned minDCF and EER. {{src:README.md#validation|Source: the README's decoding table and result.}}</p>
<div class="table-wrap"><table>
<thead><tr><th>Returned minDCF</th><th>What it means</th><th>What we do</th></tr></thead>
<tbody>
<tr><td>{{num:0.00|README.md#validation}}–{{num:0.20|README.md#validation}}</td><td>our direction; the test set behaves like our holdout</td><td>ship unchanged</td></tr>
<tr><td>{{num:0.20|README.md#validation}}–{{num:0.45|README.md#validation}}</td><td>our direction; the test set is more like In-the-Wild</td><td>switch to the most false-alarm-robust candidate</td></tr>
<tr><td>{{num:0.45|README.md#validation}}–{{num:0.90|README.md#validation}}</td><td>ambiguous</td><td>don't flip; fall back to M1b alone</td></tr>
<tr><td>{{num:0.95|README.md#validation}}–{{num:1.00|README.md#validation}}</td><td>NSA's code reads our scores inverted</td><td>ship the pre-flipped twin</td></tr>
</tbody></table></div>
<p class="callout">NSA returned minDCF {{num:0.0733|README.md#validation}} and EER {{num:3.534%|README.md#validation}}. The minDCF fell in the pre-declared {{num:0.00–0.20|README.md#validation}} band: our score direction was right, and we kept the submitted rule unchanged.</p>
