<!-- {"title": "Validation", "heading": "Validation: how we know what we know", "order": 50, "sources": ["README.md", "docs/architecture.md", "docs/reports/2026-09-26_fusion-sweep-predeclared.md", "docs/STATUS.md"], "lead": "Every number on this site comes from a split that holds out whole generators and whole speakers, never single clips. Selection uses only out-of-fold scores; the holdout is read once per model; In-the-Wild is never trained on; the test set is unlabeled and only its share above {{num:0.5|README.md#validation}} is watched. The fusion rule was chosen by rules written down before the results existed.", "description": "HEARSAY's validation: folds by generator and speaker, the outer holdout, In-the-Wild as a stress test, pre-declared sweeps, and the draft-review decoding table."} -->
<h2 id="folds">Folds by generator and speaker, never by clip</h2>
{{diagram:folds|The fold scheme: 20,000 training rows split into five inner folds that each hold out whole generators, one outer holdout read once, stress sets never trained on, and the unlabeled test set.}}
<ul>
<li><strong>The fold file</strong> has {{num:20,000|README.md#validation}} rows: 10 DiffSSD generators, LJ Speech and LibriSpeech. Fakes are grouped by {{term:generator}}; real speech by speaker (LJ, a single speaker, by chapter). Five {{term:inner folds}} each hold out whole generators: grad_tts + unit_speech, diffgan_tts + openvoicev2, pro_diff + xtts_v2, your_tts, ElevenLabs. Every learned piece of a detector, scalers and Platt maps included, is fit fold-locally, and selection uses only inner {{term:out-of-fold}} scores.</li>
<li><strong>One outer {{term:holdout}}, read once per model:</strong> PlayHT and WaveGrad2 plus 26 real-speech groups ({{num:3,858|README.md#validation}} rows). Nothing was ever trained, tuned or selected on it. Extra training data (ASVspoof 2019 real speakers, MLAAD, the rest of DiffSSD) enters inner folds only, so holdout numbers stay comparable across every model.</li>
<li><strong>The holdout has a resolution floor.</strong> With two held-out generators its noise is about ±{{num:0.07–0.10|README.md#validation}}, so we treat any gap under {{num:0.15|README.md#validation}} as noise. It can tell a good detector from a bad one, not a good fusion rule from a slightly better one.</li>
<li><strong>{{term:In-the-Wild}} is the stress test:</strong> {{num:3,000|README.md#validation}} clips ({{num:2,000|README.md#validation}} real from 54 speakers, {{num:1,000|README.md#validation}} fake), evaluation only, never trained on. For each model we report minDCF and the false-alarm rate at the threshold chosen on inner folds, under both cost weightings.</li>
<li><strong>The test set as a smoke alarm.</strong> We track the share of test files scored above {{num:0.5|README.md#validation}} against the {{num:~30%|README.md#validation}} the brief states. It flagged the band mismatch. It is never a selection signal: any monotone rescaling changes it without changing minDCF.</li>
</ul>
<p>{{src:README.md#validation|Source: the README's validation section.}}</p>
<h2 id="pre-declared">The pre-declared sweeps</h2>
<p>The fusion rule got where it is in two steps, each written down before any result was run. {{src:README.md#the-fusion-rule|Source: "The fusion rule" in the README}} and {{src:docs/reports/2026-09-26_fusion-sweep-predeclared.md#selection-rule-fixed-now|the sweep report}}.</p>
<h3 id="step-1">Step 1, frozen at 08:13</h3>
<ul>
<li><strong>Candidates:</strong> a rank blend (1−α)·rank(M1b) + α·rank(handcrafted) for α from 0 to {{num:0.5|README.md#the-fusion-rule}}; min and max rules; a cascade; a non-negative stacker shrunk toward equal weights. Then, on top of the winner, Spectra as a false-alarm suppressor.</li>
<li><strong>Rule:</strong> keep candidates within {{num:0.03|README.md#the-fusion-rule}} of the best inner out-of-fold score whose In-the-Wild minDCF under the sponsor code's cost is ≤ {{num:0.45|README.md#the-fusion-rule}}. Among those, take the best In-the-Wild minDCF under the brief's cost, with ties going to more M1b. Add Spectra suppression only if it helps In-the-Wild by ≥ {{num:0.01|README.md#the-fusion-rule}} without hurting inner or holdout by more than {{num:0.01|README.md#the-fusion-rule}}. No iteration afterward.</li>
<li><strong>Result:</strong> α = {{num:0.2|README.md#the-fusion-rule}} (tied with {{num:0.3|README.md#the-fusion-rule}}; the tie went to more M1b). Adding Spectra suppression moved In-the-Wild from {{num:0.322|README.md#the-fusion-rule}} to {{num:0.260|README.md#the-fusion-rule}} and hurt nothing, so it was applied. Final: inner {{num:0.140|README.md#the-fusion-rule}}, holdout {{num:0.014|README.md#the-fusion-rule}}, In-the-Wild {{num:0.260|README.md#the-fusion-rule}} ({{num:0.267|README.md#the-fusion-rule}} under the sponsor code's cost).</li>
</ul>
<h3 id="step-2">Step 2, the M5 addendum, ratified at noon</h3>
<ul>
<li><strong>Written at 08:35, before any run:</strong> two M5 candidates and a stricter replacement rule. Replace the frozen rule only if In-the-Wild improves by ≥ {{num:0.01|README.md#the-fusion-rule}} under the brief's cost, gets no more than {{num:0.01|README.md#the-fusion-rule}} worse under the sponsor code's, the holdout gets no more than {{num:0.05|README.md#the-fusion-rule}} worse, and inner no more than {{num:0.03|README.md#the-fusion-rule}} worse. The candidates: M5 as a second false-alarm suppressor (F) and M5 as a third rank input (A3).</li>
<li>F missed the bar: its In-the-Wild gain was {{num:0.003|README.md#the-fusion-rule}}.</li>
<li>A3 at weight {{num:0.2|README.md#the-fusion-rule}}, plus the same Spectra step, qualified: inner {{num:0.135|README.md#the-fusion-rule}} vs {{num:0.140|README.md#the-fusion-rule}}, holdout {{num:0.0065|README.md#the-fusion-rule}} vs {{num:0.014|README.md#the-fusion-rule}}, In-the-Wild {{num:0.228|README.md#the-fusion-rule}} / {{num:0.239|README.md#the-fusion-rule}} (brief / sponsor-code cost) vs {{num:0.260|README.md#the-fusion-rule}} / {{num:0.267|README.md#the-fusion-rule}}.</li>
<li>We had predicted A3 would lose on short clips and LibriSpeech real speech. With the Spectra step it improved both.</li>
<li>On the test set the switch changes little: Spearman {{num:0.974|README.md#the-fusion-rule}} against the previous rule's scores, and {{num:3 of 1,671|README.md#the-fusion-rule}} files cross {{num:0.5|README.md#the-fusion-rule}}.</li>
</ul>
<h2 id="timeline">The day, in order</h2>
<p>Times are Saturday, September 26, local to the event. Each entry links to the document that records it; where documents disagree by a few minutes the README's time is shown.</p>
<ol class="timeline">
<li><time>05:32</time>First fusion: the two detectors averaged equally. Best holdout we had; doubled the In-the-Wild misses. {{src:README.md#the-fusion-rule|README}}</li>
<li><time>08:13</time>The rule frozen by the pre-declared sweep: α = {{num:0.2|README.md#the-fusion-rule}} with Spectra suppression. {{src:README.md#the-fusion-rule|README}}</li>
<li><time>08:35</time>Two M5 candidates and a stricter replacement rule written down, before any run. {{src:README.md#the-fusion-rule|README}}</li>
<li><time>~09:15</time>Addendum results appended; {{src:README.md#numbers|A3 w 0.2 + E}} qualifies; F does not. {{src:docs/reports/2026-09-26_fusion-sweep-predeclared.md#addendum-results-appended-after-the-runs-0915-the-rule-was-not-changed|sweep report}}</li>
<li><time>09:25</time>Held: the previous rule stays the draft-review payload; the runner side is built behind a flag. {{src:README.md#the-fusion-rule|README}}</li>
<li><time>12:03</time>Nathan ratifies the switch to {{src:README.md#numbers|A3 w 0.2 + E}}. {{src:README.md#the-fusion-rule|README}}</li>
<li><time>12:30</time>The draft sent to NSA by Discord DM as CrossExam_predictions.tsv. {{src:README.md#validation|README}}</li>
<li><time>12:35</time>The runner's default switched to the shipped constants file. {{src:docs/STATUS.md#where-things-stand|STATUS}}</li>
<li><time>13:20</time>The channel-robustness lane done: λ̂ corrected, the codec hunt negative, Spectra's suppression kept, the noise weakness found. {{src:docs/STATUS.md#where-things-stand|STATUS}}</li>
</ol>
<h2 id="draft-review">The draft review</h2>
<p>For the {{term:draft review}}, we sent the exact TSV we ship on Saturday at 12:30 and decided in advance what each returned number would mean. NSA returned minDCF {{num:0.0733|README.md#validation}} and EER {{num:3.534%|README.md#validation}}. The minDCF fell in our pre-declared {{num:0.00–0.20|README.md#validation}} band, so the rule stayed unchanged; the decoding table is on <a href="metric.html#decoding">the metric page</a>. {{src:README.md#validation|Source: the README.}}</p>
