<!-- {"title": "What worked and what did not", "order": 30, "sources": ["README.md"], "lead": "The honest log. Each card names what we did, what it did, and the mechanism behind the number. The negatives are here on purpose: five shortcuts in the data, an equal-weight fusion our holdout loved and we rejected, a fine-tune that failed its gate, four detectors that cannot work on this test set, a codec hunt that came back empty, and an estimate we published and then withdrew.", "description": "HEARSAY's what-worked and what-did-not log: shortcuts found and closed, ideas rejected with their numbers and mechanisms."} -->
<h2 id="worked">What worked</h2>
<ul class="cards">
<li class="card"><h3>Band-matching the training audio to the test set</h3><p>The test set is low-passed at about {{num:7.2 kHz|README.md#what-worked}} and no training corpus is. A 71-tap Kaiser low-pass at {{num:7.25 kHz|README.md#what-worked}} on every clip, train and test, took the handcrafted detector from calling {{num:90%|README.md#what-worked}} of test files synthetic to {{num:42%|README.md#what-worked}}. Without it, everything above 7 kHz was a train-versus-test fingerprint.</p></li>
<li class="card"><h3>Real-speaker diversity, once band-matched</h3><p>Adding 40 VCTK speakers ({{term:M1b}}) improved the holdout from {{num:0.159|README.md#what-worked}} to {{num:0.072|README.md#what-worked}} and In-the-Wild from {{num:0.380|README.md#what-worked}} to {{num:0.342|README.md#what-worked}}. Before band matching, the same addition made In-the-Wild <em>worse</em> ({{num:0.374|README.md#what-worked}} → {{num:0.405|README.md#what-worked}}): the wall was hiding the gain.</p></li>
<li class="card"><h3>Length parity</h3><p>Test clips are about {{num:3.4 s|README.md#what-worked}} and training clips 5–9 s. Embedding each clip at its own length and training on crops drawn from the test-length distribution removed a repeat-padding seam that only test clips had; it was worth {{num:0.05|README.md#what-worked}} on its own for the handcrafted detector ({{num:0.709|README.md#what-worked}} → {{num:0.661|README.md#what-worked}}).</p></li>
<li class="card"><h3>Gradient-boosted trees over logistic regression</h3><p>For the handcrafted features: holdout {{num:0.374|README.md#what-worked}} vs {{num:0.661|README.md#what-worked}} on the same features. The {{term:gradient-boosted trees|trees}} transfer to unseen generators and the linear model does not.</p></li>
<li class="card"><h3>New feature families that see new generators</h3><p>CQCC frame-to-frame change and LFCC upper-coefficient variability made pro_diff visible ({{num:1.00|README.md#what-worked}} → {{num:0.32|README.md#what-worked}} out of fold) and cut inner minDCF from {{num:0.614|README.md#what-worked}} to {{num:0.434|README.md#what-worked}}.</p></li>
<li class="card"><h3>Augmented twins for the handcrafted model</h3><p>Codec round-trips and random spectral tilt, added as fit-only extra rows, cut holdout-real false alarms from {{num:9.1%|README.md#what-worked}} to {{num:6.3%|README.md#what-worked}} and In-the-Wild false alarms from {{num:0.65%|README.md#what-worked}} to {{num:0.40%|README.md#what-worked}}, and improved the holdout ({{num:0.170|README.md#what-worked}} → {{num:0.137|README.md#what-worked}}). The price was inner minDCF ({{num:0.418|README.md#what-worked}} → {{num:0.469|README.md#what-worked}}) and pro_diff ({{num:0.30|README.md#what-worked}} → {{num:0.63|README.md#what-worked}}). With a false alarm worth {{num:9.33|README.md#what-worked}} misses, we took the trade. The model is trained with augmented twins and validated on clean rows only.</p></li>
<li class="card"><h3>Treating the container as routing, not evidence</h3><p>We measured it before using it and found it was the label (below), so the detector never learns from it.</p></li>
<li class="card"><h3>Laundering both classes for compression forensics</h3><p>Re-encoding a random half of <em>both</em> classes through MP3/AAC meant the detector could not learn "MP3 = ElevenLabs/PlayHT". It then detects codec history well (AUC {{num:0.90|README.md#what-worked}}–{{num:0.94|README.md#what-worked}}).</p></li>
<li class="card"><h3>A pre-declared fusion sweep</h3><p>Writing the candidates and the selection rule down first stopped us from shipping the equal-weight rule our holdout liked best.</p></li>
<li class="card"><h3>M5 as a minority vote</h3><p>Alone it lost to the plain probe on every holdout readout. Given {{num:20%|README.md#what-worked}} of the rank blend beside M1b and the handcrafted model, it cut the fused holdout from {{num:0.014|README.md#what-worked}} to {{num:0.0065|README.md#what-worked}} and In-the-Wild from {{num:0.260|README.md#what-worked}} to {{num:0.228|README.md#what-worked}}. It errs on different files than M1b, and that is what fusion uses.</p></li>
<li class="card"><h3>Spectra-AASIST as a one-way vote</h3><p>As a false-alarm suppressor it moved In-the-Wild from {{num:0.322|README.md#what-worked}} to {{num:0.260|README.md#what-worked}} at no cost elsewhere. Used that way, if it is wrong about a file the cost is a miss, never a false alarm. The later leakage probes found the step fires only on real clips ({{num:4–5%|README.md#what-worked}} of them) and never on a fake, under every perturbation we tried.</p></li>
<li class="card"><h3>The phase cues as evidence</h3><p>Peak phase-versus-magnitude coherence separates grad_tts from real speech (AUC {{num:0.80|README.md#what-worked}}), is corpus-neutral, and names a vocoder property a person can check.</p></li>
</ul>
<h2 id="did-not-work">What did not work</h2>
<ul class="cards">
<li class="card"><h3>Five shortcuts in the data, all found and closed</h3><p><strong>Level:</strong> test clips peak near full scale and training real speech near {{num:0.5|README.md#what-did-not-work}}; peak alone predicted the label (AUC {{num:0.66|README.md#what-did-not-work}}). Closed by normalizing each input. <strong>Leading silence:</strong> LibriSpeech starts with about {{num:0.37 s|README.md#what-did-not-work}} of silence, test clips {{num:0.06 s|README.md#what-did-not-work}}. Closed by trimming both. <strong>Tiling:</strong> repeat-padding short test clips put a seam only in test data. Closed by length parity. <strong>Container:</strong> every test file is 16 kHz PCM WAV with the same FFmpeg tag. Closed by one decode path. <strong>The {{num:7.2 kHz|README.md#what-did-not-work}} wall:</strong> closed by band matching.</p></li>
<li class="card"><h3>The codec hunt came back empty</h3><p>We checked whether the wall is a codec, to reproduce it more faithfully in training. It isn't: across 34 MP3 and AAC settings none matched it better than our own Kaiser low-pass (the closest was {{num:3%|README.md#what-did-not-work}} nearer on distance and worse on spectral holes). It is a smooth low-pass, like a resampler's anti-alias filter, so the planned symmetric codec refit never ran.</p></li>
<li class="card"><h3>The container is the label</h3><p>LibriSpeech is FLAC, LJ is 22 kHz WAV, and DiffSSD's ElevenLabs and PlayHT are MP3. PlayHT's MP3s carry the exact encoder tag that all {{num:1,671|README.md#what-did-not-work}} test files carry. A learned metadata model would score perfectly on our holdout for the wrong reason, then call the whole test set PlayHT. The container detector returns a constant {{num:0.5|README.md#what-did-not-work}} on this test set by design.</p></li>
<li class="card"><h3>Compression forensics sees the pipeline, not the class</h3><p>With codec history equalized, class holdout minDCF is {{num:0.90|README.md#what-did-not-work}}, and it calls {{num:81%|README.md#what-did-not-work}} of the test set synthetic, because the test set reads as laundered throughout (mean P(laundered) {{num:0.62|README.md#what-did-not-work}}). It stays as evidence.</p></li>
<li class="card"><h3>ENF cannot be validated here</h3><p>Stable mains hum is in {{num:36%|README.md#what-did-not-work}} of LJ Speech clips (a home studio) and {{num:21%|README.md#what-did-not-work}} of LibriSpeech, and in almost no generated audio, so a learned version would learn "hum = LJ = real". Only 24 test files carry hum. Rule-based and mild on purpose; evidence only.</p></li>
<li class="card"><h3>Splice finds vocoder artifacts, not edits</h3><p>On training data the seams are single-sample clicks in {{num:27%|README.md#what-did-not-work}} of WaveGrad2 and DC jumps in 9–{{num:13%|README.md#what-did-not-work}} of several generators <em>and</em> {{num:9%|README.md#what-did-not-work}} of LibriSpeech. The sponsor said no test clip is partially synthetic. It flags 58 test files; evidence only.</p></li>
<li class="card"><h3>Speaker drift points the wrong way</h3><p>Fakes are the <em>most</em> self-consistent voices: mean window-to-window similarity separates them toward fake at AUC {{num:0.73|README.md#what-did-not-work}}. A cloned voice doesn't vary from second to second the way a person does. Drift flags {{num:16%|README.md#what-did-not-work}} of test files, mostly the hard real recordings. Fused, it would push those toward synthetic, so it is evidence only.</p></li>
<li class="card"><h3>Fine-tuning XLS-R lost to a frozen probe</h3><p>Fine-tuning all 12 kept layers fit the seen generators and transferred worse to the unseen commercial one: {{num:0.38–0.41|README.md#what-did-not-work}} on the ElevenLabs fold vs {{num:0.31|README.md#what-did-not-work}} with the backbone frozen. The frozen-backbone head then lost to the plain probe on the holdout ({{num:0.363|README.md#what-did-not-work}} vs {{num:0.159|README.md#what-did-not-work}}), on WaveGrad2, on LibriSpeech real speech and on clips under 4 s ({{num:0.60|README.md#what-did-not-work}}). It won only on In-the-Wild false alarms ({{num:0.45%|README.md#what-did-not-work}} vs {{num:0.7%|README.md#what-did-not-work}}). Its one use is as a {{num:20%|README.md#what-did-not-work}} voice in fusion. Twelve A100 instances, ${{num:5.42|README.md#what-did-not-work}} in total.</p></li>
<li class="card"><h3>Pruning corpus-cue columns hurt every time</h3><p>83 handcrafted columns separate LJ from LibriSpeech more than they separate real from fake. Dropping them made every readout worse, including LibriSpeech false alarms ({{num:0.54|README.md#what-did-not-work}} → {{num:0.59–0.61|README.md#what-did-not-work}}); stripping v3's own cue columns took it from {{num:0.614|README.md#what-did-not-work}} to {{num:0.848|README.md#what-did-not-work}}. The check told us which per-source numbers to read, not which columns to delete.</p></li>
<li class="card"><h3>The handcrafted detector's test-domain offset</h3><p>Even band-matched, the test recordings have a darker, codec-like spectral envelope. The {{num:234|README.md#what-did-not-work}} columns tell train from test at AUC {{num:0.99|README.md#what-did-not-work}}, and {{num:84%|README.md#what-did-not-work}} of the shifted columns move toward "fake". Pruning the shifted columns made it worse (the rest still separate at {{num:0.98|README.md#what-did-not-work}}); augmentation removed only part of it. This is part of why it gets {{num:20%|README.md#what-did-not-work}} of the vote, not half.</p></li>
<li class="card"><h3>grad_tts is invisible to the handcrafted model under our validation</h3><p>Its phase cue is shown by no other generator, so when grad_tts is the held-out one, nothing teaches the cue: {{num:1.00|README.md#what-did-not-work}} in every variant. That is an honest limit of holding out by generator.</p></li>
<li class="card"><h3>Prosody beyond pitch</h3><p>Pause fraction and count, voiced fraction, loudness dynamics and zero-crossing rate all sat within {{num:0.05|README.md#what-did-not-work}} of chance.</p></li>
<li class="card"><h3>Equal-weight fusion: rejected</h3><p>Our first fusion averaged the two detectors equally. On the holdout it looked like the best thing we had: {{num:0.018|README.md#the-fusion-rule}} and {{num:0.015|README.md#the-fusion-rule}}, against {{num:0.072|README.md#the-fusion-rule}} for M1b alone. On In-the-Wild it doubled the misses, from {{num:28%|README.md#the-fusion-rule}} for M1b alone to 58–{{num:60%|README.md#the-fusion-rule}}, and pushed the share of test files called synthetic up to 32–{{num:40%|README.md#the-fusion-rule}}. The holdout gain was below the holdout's resolution floor; the In-the-Wild loss was large and consistent. The handcrafted column is excellent on generators it has seen and blind to web-sourced fakes ({{num:97%|README.md#the-fusion-rule}} missed on its own), so giving it half the vote traded real-world detection for a holdout number.</p></li>
<li class="card"><h3>Spectra kept out of the vote, though a full vote scores better</h3><p>With M5 in the blend, fusing everything equally beats the shipped rule on every labeled readout (holdout {{num:0.0045|README.md#orchestration-what-routing-changes}}, In-the-Wild {{num:0.214|README.md#orchestration-what-routing-changes}} and {{num:0.196|README.md#orchestration-what-routing-changes}}). It does so by giving Spectra-AASIST a full vote. We ruled that out before seeing these numbers, because Spectra's training data is undisclosed and our validation rows may be in its training set. The choice rests on that argument, not on these readouts.</p></li>
<li class="card"><h3>Our holdout overstates real-world skill</h3><p>Every XLS-R probe we trained sits at {{num:0.34–0.41|README.md#what-did-not-work}} on In-the-Wild against {{num:0.07–0.16|README.md#what-did-not-work}} on the holdout, and the handcrafted model gets {{num:1.00|README.md#what-did-not-work}} there. Channel robustness, not more read speech or more fake data, is the gap we did not close. A classifier separating our holdout's real speech from In-the-Wild's, run over the test files, puts the wild share at λ̂ = {{num:0.51|README.md#what-did-not-work}} ({{num:95%|README.md#what-did-not-work}} CI {{num:0.12–0.64|README.md#what-did-not-work}}). The test set is partly wild, so neither validation set represents it alone; the shipped rule beats the previous one on both, so the choice does not depend on λ.</p></li>
<li class="card"><h3>A pretrained model we can't audit, then probed</h3><p>Spectra-AASIST separates our inner rows perfectly (AUC {{num:1.000|README.md#what-did-not-work}}). Its model card names no training set, so its inner, holdout and In-the-Wild numbers may all be in-sample. We probed for the symptoms of memorisation instead: on {{num:500|README.md#what-did-not-work}} holdout clips under four label-preserving changes it was the most stable detector (mean |ΔAUC| {{num:0.0008|README.md#what-did-not-work}}, against {{num:0.0041|README.md#what-did-not-work}} for M1b); on {{num:572|README.md#what-did-not-work}} MLAAD clips from {{num:143|README.md#what-did-not-work}} generators it had the lowest miss rate ({{num:14.9%|README.md#what-did-not-work}}, against {{num:22.7%|README.md#what-did-not-work}} for M1b, {{num:28.7%|README.md#what-did-not-work}} for M5, {{num:56%|README.md#what-did-not-work}} for the handcrafted model); its suppression step never raised the fused holdout cost. Verdict: keep it as a suppressor only. The one number we still can't trust is its In-the-Wild score, because its authors evaluated on that set.</p></li>
<li class="card"><h3>Peak-normalizing Spectra's input</h3><p>A fix for its within-fake level correlation cost {{num:0.033|README.md#what-did-not-work}} on real speech and did not remove the correlation, so the level was a proxy, not the cue. Rejected.</p></li>
<li class="card"><h3>Additive noise is the shipped rule's weak spot</h3><p>At 20 dB SNR white noise on {{num:500|README.md#what-did-not-work}} holdout clips the handcrafted model loses almost all discrimination (AUC {{num:0.998|README.md#what-did-not-work}} → {{num:0.64|README.md#what-did-not-work}}, minDCF {{num:0.048|README.md#what-did-not-work}} → {{num:0.996|README.md#what-did-not-work}}); M1b rises from {{num:0.056|README.md#what-did-not-work}} to {{num:0.271|README.md#what-did-not-work}}, and the shipped rule from {{num:0.012|README.md#what-did-not-work}} to {{num:0.269|README.md#what-did-not-work}}. Spectra holds at {{num:0.116|README.md#what-did-not-work}}, but noise pushes it out of its "strongly real" region, so its suppression step never fires. Found after the rule was frozen and not fixed; the pointer is noise augmentation of the handcrafted training, applied to both classes.</p></li>
<li class="card"><h3>A wild real-speech corpus, planned and not attempted</h3><p>It was the fusion consult's suggested fix for the In-the-Wild gap. We dropped it at 12:16 on Saturday because a download, extraction and refit would not fit the time box, and the time went to the Spectra probes and the λ estimate. The two candidates looked unusable anyway: VoxCeleb1's test set needs a request form, and SpoofCeleb's real speech has been speech-enhanced.</p></li>
<li class="card"><h3>Our first estimate of how wild the test set is was wrong</h3><p>It said λ̂ = {{num:0.947|README.md#what-did-not-work}} with a classifier AUC of {{num:0.99|README.md#what-did-not-work}}, and read "wild" as "codec-processed". One feature did the work: a whole-spectrogram noise-floor percentile that landed in the 7–8 kHz stopband. It was measuring the test files' double low-pass, not the recording channel: one MP3 round-trip moved {{num:91%|README.md#what-did-not-work}} of our clean clips to "wild". Dropping that feature, under the rule we had already declared for columns above 7 kHz, gave {{num:0.51|README.md#what-did-not-work}} (MP3 control {{num:91%|README.md#what-did-not-work}} → {{num:9%|README.md#what-did-not-work}}). The same kind of shortcut as the {{num:7.2 kHz|README.md#what-did-not-work}} wall, read through a feature that didn't look like a band feature.</p></li>
</ul>
