<!-- {"title": "The channel-robustness probes", "group": "Validation", "order": 73, "lead": "Three diagnostic scripts run on Saturday afternoon: how wild is the test set, is the {{num:7.2 kHz|README.md#what-worked}} wall a codec, and is the off-the-shelf Spectra model memorising. Diagnostic only: no TSV, no rule change.", "sources": ["scripts/channel_lambda.py", "scripts/channel_codec.py", "scripts/m3_probes.py", "docs/reports/2026-09-26_channel-robustness.md"]} -->
<h2 id="plain">In plain words</h2>
<p>The holdout and In-the-Wild disagree about every model, so which one the test set resembles matters. λ̂ estimates that. The wall in the test spectrum might have been a codec we could reproduce in training; the codec hunt checked. And Spectra-AASIST's training data is unknown, so three probes looked for the symptoms of memorisation instead of the cause. The results are on <a href="../what-worked.html#did-not-work">What did not work</a>; this page is what the scripts do and how their rules were set before the runs.</p>
<h2 id="io">What goes in and comes out</h2>
<p>In: holdout real speech, In-the-Wild real speech, the test files, control sets, and for the probes the shipped models and constants. Out: JSON and CSV readouts under the outputs directory, and one verdict per pre-declared rule.</p>
<h2 id="where">Where it lives</h2>
<p>{{src:scripts/channel_lambda.py|channel_lambda.py}} (λ̂), {{src:scripts/channel_codec.py|channel_codec.py}} (the codec grid), {{src:scripts/m3_probes.py|m3_probes.py}} (the Spectra probes); the pre-declared rules in {{src:docs/specs/2026-09-26_channel-robustness.md|the run spec}}.</p>
<h2 id="params">Methods and where each is set</h2>
<ul>
<li><strong>λ̂.</strong> Label-free channel statistics (the compression features plus noise-floor level and stationarity, a decay proxy, flatness, loudness spread, pause fraction) on identically prepared clips; columns reading above 7 kHz dropped because the test files carry two low-passes. A logistic classifier separates holdout real speech from In-the-Wild real speech with speaker-grouped out-of-fold scoring; λ̂ is adjusted classify-and-count, refused when the classifier is too weak, with a cluster bootstrap by speaker ({{src:scripts/channel_lambda.py#L119|channel_lambda.py, lines 119–207}}). The crossover the consult named is {{num:0.32|scripts/channel_lambda.py#L34}}. An identifiability rule (classifier AUC, control shares, an LJ-removed sensitivity) must pass before λ̂ is read.</li>
<li><strong>The codec grid.</strong> {{num:100|docs/reports/2026-09-26_channel-robustness.md#b-is-the-72-khz-wall-a-codec}} inner real clips through MP3 and AAC at several bitrates and two encode rates, alone and followed by our own low-pass, compared with all test files on high-band statistics; a codec "matches" only if it is at least {{num:20%|docs/reports/2026-09-26_channel-robustness.md#b-is-the-72-khz-wall-a-codec}} closer than the low-pass alone and closer on both hole statistics ({{src:scripts/channel_codec.py#L101|channel_codec.py, lines 101–117}}).</li>
<li><strong>The Spectra probes.</strong> {{num:500|README.md#what-did-not-work}} holdout clips under four label-preserving perturbations (an MP3 round-trip re-aligned by cross-correlation, white noise at 20 dB SNR, {{num:±2%|README.md#what-did-not-work}} speed, a one-sample shift); {{num:600|docs/specs/2026-09-26_channel-robustness.md}} MLAAD clips planned for the unseen-generator miss rate ({{num:572|README.md#what-did-not-work}} run, four per model); and the Spearman agreement of the probe and Spectra on holdout versus test rows. The verdict rule: the suppression step is "at risk" if Spectra is markedly less stable than the probe, if the shipped rule damps more than {{num:5%|docs/reports/2026-09-26_channel-robustness.md#e-is-m3-memorising-and-what-does-its-suppression-step-cost}} of unseen fakes, or if the step ever raises the fused holdout cost by more than {{num:0.01|docs/reports/2026-09-26_channel-robustness.md#e-is-m3-memorising-and-what-does-its-suppression-step-cost}} ({{src:scripts/m3_probes.py#L125|m3_probes.py, lines 125–142}}).</li>
</ul>
<h2 id="status">Status</h2>
<p>Done at 13:20 on Saturday. The symmetric codec refit was pre-declared and not run because no codec matched; the wild real-speech corpus was dropped for the time box.</p>
<h2 id="numbers">Numbers</h2>
<p>λ̂ = {{num:0.51|README.md#what-did-not-work}} ({{num:95%|README.md#what-did-not-work}} CI {{num:0.12–0.64|README.md#what-did-not-work}}), after a first estimate of {{num:0.947|README.md#what-did-not-work}} was withdrawn. The closest codec was {{num:3%|README.md#what-did-not-work}} nearer than the low-pass. Spectra's mean |ΔAUC| {{num:0.0008|README.md#what-did-not-work}} against {{num:0.0041|README.md#what-did-not-work}} for the probe; MLAAD miss rate {{num:14.9%|README.md#what-did-not-work}}. The new weak spot: at 20 dB white noise the handcrafted model's AUC falls from {{num:0.998|README.md#what-did-not-work}} to {{num:0.64|README.md#what-did-not-work}} and the shipped rule's holdout cost rises from {{num:0.012|README.md#what-did-not-work}} to {{num:0.269|README.md#what-did-not-work}}.</p>
<h2 id="limits">Known limits</h2>
<p>λ̂ rests on a handful of hole statistics and is a weak, single-method estimate; the identifiability rule passed only just. The agreement gap between the probe and Spectra is descriptive, not evidence of memorisation, because the two sets differ in class mix and generators.</p>
<h2 id="tests">Tests that pin it</h2>
<p><code>tests/test_channel_robustness.py</code>, hermetic: statistics finite on degenerate inputs and level-invariant, noise raises the floor, a reverb tail slows the decay, grouped folds never split a group and the leak check can fail, the adjusted estimate recovers known mixtures and refuses a weak classifier, the mean posterior's bias, the identifiability rule fails on each guard alone, novelty share, each perturbation changes the signal and none does not, noise hits 20 dB, the shift is one sample, speed changes length by two percent, the codec alignment restores length, ΔAUC sign, the verdict rule on each guard alone, the high-band statistics see the wall, the match rule needs distance and both hole statistics.</p>
<h2 id="sources">Sources</h2>
<p>{{src:docs/reports/2026-09-26_channel-robustness.md|The report}}; {{src:docs/specs/2026-09-26_channel-robustness.md|the run spec}}; {{src:docs/reports/2026-09-26_channel-robustness-plan.md|the plan}}.</p>
