<!-- {"title": "Compression forensics", "group": "Engineered detectors", "order": 41, "lead": "Nineteen features that read the traces a lossy codec leaves in the upper band, trained with both classes laundered so the model cannot learn that MP3 means a particular generator. It detects codec history well and the class barely, so it is evidence and routing, never score.", "sources": ["src/hearsay/compression.py", "src/hearsay/detectors/compression.py", "docs/reports/2026-09-26_cpu-detectors.md"]} -->
<h2 id="plain">In plain words</h2>
<p>{{term:compression forensics|Compression forensics}}: a codec leaves holes and floors in the spectrum. On our training data the fakes from two commercial generators arrive as MP3 and the real speech does not, so a naive compression detector would score perfectly by reading the format. We re-encode ({{term:laundering|launder}}) a random half of <em>both</em> classes before training, which leaves it nothing to learn but the actual traces. What it then finds is that the whole test set reads as laundered, which says something about how the test set was made and nothing about which files are fake.</p>
<h2 id="io">What goes in and comes out</h2>
<p>In: the prepared clip. Out: the 19 features and a probability from trees, a sentence such as <code>compression-trace features synthetic-like (P=0.97): whole-clip floor depth 1.7 SD below real speech (toward synthetic); …</code>, and the routing fact of the clip's effective bandwidth.</p>
<h2 id="where">Where it lives</h2>
<p>Features and laundering in {{src:src/hearsay/compression.py|compression.py}}; the detector in {{src:src/hearsay/detectors/compression.py|detectors/compression.py}}; extraction in {{src:scripts/extract_compression.py|extract_compression.py}}; trained by the same trainer as the handcrafted detector with its own prefix.</p>
<h2 id="params">Parameters and where each is set</h2>
<ul>
<li><strong>Analysis:</strong> {{num:1,024|src/hearsay/compression.py#L35}}-point frames; the hole band {{num:3,000|src/hearsay/compression.py#L40}}–{{num:7,000|src/hearsay/compression.py#L40}} Hz; a deep hole is 75 dB below the clip's peak and a local hole 30 dB below the frame's band median ({{src:src/hearsay/compression.py#L35|compression.py, lines 35–40}}).</li>
<li><strong>The 19 features:</strong> effective bandwidth (the highest quarter-kilohertz band from 3 kHz up within 40 dB of the 1–3 kHz level), four band levels from 4 to 8 kHz relative to 1–3 kHz, the high-band slope, eight deep- and local-hole statistics (fraction, flicker, persistence, runs), and five floor statistics including the valley depth and the low-band floor ({{src:src/hearsay/compression.py#L46|compression.py, lines 46–102}}).</li>
<li><strong>Laundering:</strong> an FFmpeg encode as MP3 (three times in four) or AAC at a bitrate from {{num:24|src/hearsay/compression.py#L42}} to {{num:128|src/hearsay/compression.py#L42}} kbps and an encode rate of {{num:16,000|src/hearsay/compression.py#L43}}, {{num:22,050|src/hearsay/compression.py#L43}} or {{num:44,100|src/hearsay/compression.py#L43}} Hz, decoded back to 16 kHz ({{src:src/hearsay/compression.py#L41|compression.py, lines 41–147}}); the training run laundered half the rows, drawn per row from a seeded generator.</li>
<li><strong>Routing:</strong> the runner reports the bandwidth against the {{num:7,250|src/hearsay/pipeline.py#L618}} Hz band match, and the container's facts decide whether the result is "run for evidence" or "applies" ({{src:src/hearsay/pipeline.py#L605|pipeline.py, lines 605–619}}).</li>
</ul>
<h2 id="status">Status</h2>
<p>Built and exported; evidence and routing only, by the leave-one-out rule set in the plan.</p>
<h2 id="numbers">Numbers</h2>
<p>Codec history: AUC {{num:0.90|README.md#what-worked}}–{{num:0.94|README.md#what-worked}}. Class: inner {{num:0.931|README.md#numbers}}, holdout {{num:0.900|README.md#numbers}} (EER {{num:20.1%|README.md#numbers}}); it calls {{num:80.7%|README.md#numbers}} of the test set synthetic because the test set reads as laundered throughout (mean P(laundered) {{num:0.62|README.md#what-did-not-work}}). Bandwidth inventory of the test set: {{num:981|README.md#orchestration-what-routing-changes}} files at {{num:7,250|README.md#orchestration-what-routing-changes}} Hz, {{num:670|README.md#orchestration-what-routing-changes}} at {{num:7,500|README.md#orchestration-what-routing-changes}} Hz, 12 full band, 8 at 5–7 kHz.</p>
<h2 id="limits">Known limits</h2>
<p>It describes a file's processing history, not the voice. The codec hunt found that the test set's wall is not an MP3 or AAC round-trip at any tested setting, so its "laundered" reading of the test set is a low-pass signature rather than a codec's. A comment in the module names a 3–8 kHz median where the code uses 3–7 kHz.</p>
<h2 id="tests">Tests that pin it</h2>
<p><code>tests/test_compression_detector.py</code>: features finite and matching their labels, the band match pulls the effective bandwidth below the cutoff, laundering leaves traces (needs an MP3 encoder), an unknown codec is rejected, draws are reproducible, the contract, direction, the sentence names traces and standard deviations, memoization, a missing model is an error, registration, the scripts exist. <code>tests/test_pipeline.py</code> pins the <code>7250 Hz</code> routing line.</p>
<h2 id="sources">Sources</h2>
<p>{{src:docs/reports/2026-09-26_cpu-detectors.md|The CPU detectors report, "Compression forensics detector"}}; {{src:docs/reports/2026-09-26_channel-robustness.md#b-is-the-72-khz-wall-a-codec|the codec hunt}}; {{src:docs/architecture.md#7-engineered-detectors|Architecture §7}}.</p>
