<!-- {"title": "The Docker image", "group": "Delivery", "order": 80, "lead": "An offline, CPU-only image whose entrypoint is the runner, with every model and weight inside, a hash manifest checked at start, and a refusal to run if the network is on. Not a graded deliverable since Saturday noon; kept as evidence that the pipeline runs from a clean build.", "sources": ["Dockerfile", "docker/build.sh", "docker/entrypoint.sh", "docs/specs/2026-09-26_k-docker-image.md"]} -->
<h2 id="plain">In plain words</h2>
<p>The brief originally asked for a container that scores the test set without configuration. NSA said on Saturday that the TSV and the README are the submission, so the image became a reproducibility check rather than a deliverable. It still proves the claim that nothing on the scoring path needs a network: the build bakes the offline flags in, the entrypoint verifies every shipped file against a manifest, and the smoke test confirms that an online container is refused.</p>
<h2 id="io">What goes in and comes out</h2>
<p>In: a mounted directory of audio, the template TSV, and the team name in an environment variable. Out: the same outputs as the runner, in a mounted output directory.</p>
<h2 id="where">Where it lives</h2>
<p>{{src:Dockerfile|Dockerfile}}; {{src:docker/build.sh|docker/build.sh}} (stages the model bundles, builds for linux/amd64, tags by timestamp); {{src:docker/entrypoint.sh|docker/entrypoint.sh}} (threads, template discovery, manifest check, the runner); {{src:docker/assets.py|docker/assets.py}} (the manifest); {{src:docker/smoke.sh|docker/smoke.sh}}; {{src:docker/parity.py|docker/parity.py}}.</p>
<h2 id="params">Parameters and where each is set</h2>
<ul>
<li>Base image <code>python:{{num:3.12|Dockerfile#L7}}-slim-bookworm</code> pinned by digest; FFmpeg from apt; CPU-only torch {{num:2.14.0|Dockerfile#L29}} from the PyTorch CPU index; locked dependencies exported without torch, torchaudio or LightGBM ({{src:Dockerfile#L7|Dockerfile, lines 7–30}}).</li>
<li>Offline flags baked in as environment: Hugging Face and transformers offline, telemetry off ({{src:Dockerfile#L9|Dockerfile, lines 9–12}}).</li>
<li>Copied in: the XLS-R, Spectra-AASIST and ECAPA weights, the staged model bundles, the source and scripts; a manifest of every shipped file's size and hash is frozen at build time and verified at every start, exit code 3 on a mismatch ({{src:docker/entrypoint.sh#L36|entrypoint.sh, lines 36–39}}).</li>
<li>Threads: the container's CPU quota, capped at six ({{src:docker/entrypoint.sh#L12|entrypoint.sh, lines 12–25}}); a lone TSV in the data mount becomes the template; the runner is started with <code>--require-offline</code>.</li>
<li>The build stages the probe, the handcrafted and compression bundles and every fusion constants file, refuses to run with less than eight gigabytes free, and records a build-info line with the git commit ({{src:docker/build.sh#L21|build.sh, lines 21–69}}).</li>
</ul>
<h2 id="status">Status</h2>
<p>The recorded image is <code>hearsay:20260926-0916</code>, built from source <code>37c26b8</code>, running the <strong>previous</strong> rule: it does not contain the M5 checkpoint. The build script does not stage M5, so a rebuild as-is would refuse to start under the runner's current default; staging M5 adds about {{num:627 MB|docs/specs/2026-09-26_k-docker-image.md}}. Both facts are on the routed list.</p>
<h2 id="numbers">Numbers</h2>
<p>{{num:50|README.md#reproduce-in-docker-offline-cpu-linuxamd64-not-a-graded-deliverable}} test files scored inside the image against the previous rule's TSV: Spearman {{num:1.0|README.md#reproduce-in-docker-offline-cpu-linuxamd64-not-a-graded-deliverable}}, max abs diff {{num:2.02e-4|README.md#reproduce-in-docker-offline-cpu-linuxamd64-not-a-graded-deliverable}}; decoded audio identical to the Mac on 50 of 50 files; about {{num:4 s|README.md#reproduce-in-docker-offline-cpu-linuxamd64-not-a-graded-deliverable}} per file under emulation; {{num:3.3 GiB|README.md#reproduce-in-docker-offline-cpu-linuxamd64-not-a-graded-deliverable}} resident.</p>
<h2 id="limits">Known limits</h2>
<p>Built on Apple Silicon under emulation, so it is slow there. The entrypoint's comment still names an old default rule. The image is not the shipped rule; the runner on the Mac is.</p>
<h2 id="tests">Tests that pin it</h2>
<p><code>tests/test_docker_image.py</code> (no Docker needed): base image and FFmpeg layer, offline environment baked in, CPU torch and no LightGBM in the locked dependencies, the context never copies private trees or the frontend, copy destinations match the loaders, the entrypoint's contract matches the runner including the six-thread cap, symlinked bundles resolve, no LightGBM on the image path, the manifest freezes, verifies and detects tampering, the PCM hash detects a changed sample, the smoke script runs offline and checks order, the build script targets amd64 and records provenance.</p>
<h2 id="sources">Sources</h2>
<p>{{src:docs/specs/2026-09-26_k-docker-image.md|The run spec}}; {{src:docs/reports/2026-09-26_k-docker-image-plan.md|the plan}}; {{src:README.md#reproduce-in-docker-offline-cpu-linuxamd64-not-a-graded-deliverable|README, "Reproduce in Docker"}}.</p>
