<!-- {"title": "The pre-declared sweeps and the orchestration ablation", "group": "Fusion", "order": 51, "lead": "Two scripts that chose the fusion rule under rules written before they ran, and one that measures what the router changes by switching each rule off. Together they are the record of how the shipped rule was picked and what it buys.", "sources": ["scripts/fuse_sweep.py", "scripts/fuse_sweep_m5.py", "scripts/orchestration_ablation.py", "docs/reports/2026-09-26_fusion-sweep-predeclared.md"]} -->
<h2 id="plain">In plain words</h2>
<p>Our first fusion, an equal-weight average, was the best thing our holdout had ever seen and doubled the misses on real-world audio. The lesson was to write the candidates, the readouts and the selection rule down first and apply them once. The first sweep froze the rule at 08:13; a second, stricter sweep for M5 was written at 08:35, run by 09:15 and ratified at noon. The ablation exists because the rubric's orchestration bonus deserves a measurement, not a claim.</p>
<h2 id="io">What goes in and comes out</h2>
<p>In: the detectors' exported score files (inner out-of-fold, holdout, test and In-the-Wild rows). Out: a table of every candidate under every readout, a decision under the fixed rule, the constants file when asked, and for the ablation a markdown and JSON table of the router on, each rule off, and everything fused equally.</p>
<h2 id="where">Where it lives</h2>
<p>{{src:scripts/fuse_sweep.py|fuse_sweep.py}} (the first sweep), {{src:scripts/fuse_sweep_m5.py|fuse_sweep_m5.py}} (the M5 addendum and the unexercised refit rule), {{src:scripts/orchestration_ablation.py|orchestration_ablation.py}}, {{src:scripts/fuse.py|fuse.py}} (the first, rejected fusion).</p>
<h2 id="params">The rules, as written before the runs</h2>
<ul>
<li><strong>First sweep, candidates:</strong> the rank blend for α from 0 to {{num:0.5|README.md#the-fusion-rule}}; min and max rules; a cascade; a non-negative stacker shrunk toward equal weights; then Spectra as a suppressor on top of the winner. <strong>Rule:</strong> admissible if within {{num:0.03|README.md#the-fusion-rule}} of the best inner score and In-the-Wild under the sponsor code's cost at most {{num:0.45|README.md#the-fusion-rule}}; among those the best In-the-Wild under the brief's cost, ties to more M1b; Spectra added only if it helps In-the-Wild by at least {{num:0.01|README.md#the-fusion-rule}} without hurting inner or holdout by more than {{num:0.01|README.md#the-fusion-rule}}; no iteration ({{src:scripts/fuse_sweep.py#L121|fuse_sweep.py, lines 121–143}}).</li>
<li><strong>M5 addendum, candidates:</strong> M5 as a second suppressor with a threshold at the first percentile of inner spoof logits (which turned out to be {{num:−3.90|docs/reports/2026-09-26_fusion-sweep-predeclared.md#addendum-results-appended-after-the-runs-0915-the-rule-was-not-changed}}), and M5 as a third rank input at weight {{num:0.1|docs/reports/2026-09-26_fusion-sweep-predeclared.md#addendum-m5-candidates-pre-declared-before-any-run-sat-0835-requested-by-nathan-via-the-oversight-chat}} or {{num:0.2|docs/reports/2026-09-26_fusion-sweep-predeclared.md#addendum-m5-candidates-pre-declared-before-any-run-sat-0835-requested-by-nathan-via-the-oversight-chat}}, each with and without the Spectra step. <strong>Rule:</strong> replace only if In-the-Wild improves by at least {{num:0.01|README.md#the-fusion-rule}} under the brief's cost, worsens by at most {{num:0.01|README.md#the-fusion-rule}} under the sponsor code's, the holdout worsens by at most {{num:0.05|README.md#the-fusion-rule}} and inner by at most {{num:0.03|README.md#the-fusion-rule}} ({{src:scripts/fuse_sweep_m5.py#L114|fuse_sweep_m5.py, lines 114–117}}).</li>
<li><strong>A third rule, for a refit probe column</strong> that a codec match would have produced, was written at 12:50 and never exercised because no codec matched; a self-check showed it returning "keep" on the shipped column.</li>
<li><strong>The ablation</strong> re-fuses the exports with the Spectra step and the gate each on or off, and adds a four-way equal rank mean including Spectra; it reports both cost readings on the holdout and In-the-Wild, the test share above 0.5, and how many files each rule touched ({{src:scripts/orchestration_ablation.py#L124|orchestration_ablation.py, lines 124–141}}). Its default constants file is the previous rule; the shipped table was produced by pointing it at the shipped file.</li>
</ul>
<h2 id="status">Status</h2>
<p>Both sweeps applied once; the M5 candidate held from 09:25 until noon while the runner side was built behind a flag, then ratified. The advance expectation that the three-way blend would lose on short clips and LibriSpeech real speech was wrong: with the Spectra step it improved both.</p>
<h2 id="numbers">Numbers</h2>
<p>First sweep: α = {{num:0.2|README.md#the-fusion-rule}} won (tied with {{num:0.3|README.md#the-fusion-rule}}), Spectra took In-the-Wild from {{num:0.322|README.md#the-fusion-rule}} to {{num:0.260|README.md#the-fusion-rule}}. Addendum: the suppressor candidate gained only {{num:0.003|README.md#the-fusion-rule}}; the three-way blend at {{num:0.2|README.md#the-fusion-rule}} qualified with holdout {{num:0.0065|README.md#the-fusion-rule}} against {{num:0.014|README.md#the-fusion-rule}} and In-the-Wild {{num:0.228|README.md#the-fusion-rule}} against {{num:0.260|README.md#the-fusion-rule}}. Ablation: the Spectra step takes the holdout from {{num:0.0200|README.md#orchestration-what-routing-changes}} to {{num:0.0065|README.md#orchestration-what-routing-changes}} and In-the-Wild from {{num:0.274|README.md#orchestration-what-routing-changes}} to {{num:0.229|README.md#orchestration-what-routing-changes}}, touching only real files; the gate touches 0 test files; fusing everything equally reaches {{num:0.0045|README.md#orchestration-what-routing-changes}} and {{num:0.214|README.md#orchestration-what-routing-changes}} by giving Spectra a full vote. The full table is on <a href="../how-it-decides.html#router-measured">How it decides</a>.</p>
<h2 id="limits">Known limits</h2>
<p>The holdout's resolution floor means the sweeps could not have told a good rule from a slightly better one on the holdout alone; the rules lean on In-the-Wild for that reason. The ablation script has no tests of its own.</p>
<h2 id="tests">Tests that pin it</h2>
<p><code>tests/test_pipeline.py</code> pins that the runner's arithmetic equals each sweep script's, including the left-sided rank boundary and the strict Spectra inequalities, and that the shipped constants file reproduces the 09:14 candidate TSV from the exported logits (data-gated).</p>
<h2 id="sources">Sources</h2>
<p>{{src:docs/reports/2026-09-26_fusion-sweep-predeclared.md|The sweep report}}; {{src:README.md#the-fusion-rule|README, "The fusion rule"}}; {{src:README.md#orchestration-what-routing-changes|README, "Orchestration"}}; {{src:docs/consults/2026-09-26_fusion-strategy_RESPONSE.md|the fusion consult}}.</p>
