<!-- {"title": "The fusion rule", "group": "Fusion", "order": 50, "lead": "Three detectors are turned into ranks against their own training distributions, blended with fixed weights, checked once by Spectra-AASIST, which may only halve a high rank, and mapped through a Platt map into a probability. Everything it needs is in one constants file that the runner never refits.", "sources": ["src/hearsay/pipeline.py", "scripts/fuse_sweep_m5.py", "README.md"]} -->
<h2 id="plain">In plain words</h2>
<p>The metric only sees the order of our scores, so the fusion is a {{term:rank blend}}: each detector's raw score becomes "what share of my training rows scored below this", and those shares are averaged with weights. That stops one detector's scale from dominating and makes the rule easy to read. The weights were not fitted; they were chosen by a selection rule written down before any result (see <a href="fusion-sweeps.html">the sweeps</a>). The <a href="../how-it-decides.html#worked-file">worked file</a> shows the arithmetic on a real test file.</p>
<h2 id="io">What goes in and comes out</h2>
<p>In: the logits of <code>m1b_v3</code>, <code>handcrafted_v5</code>, <code>m5_xlsr_ft</code> and <code>spectra_aasist</code> for a file. Out: the base rank, whether the Spectra step fired, the Platt probability, and, after the policy, the final score.</p>
<h2 id="where">Where it lives</h2>
<p><code>FusionConstants</code> in {{src:src/hearsay/pipeline.py#L132|pipeline.py, lines 132–328}} (parsing, validation, the arithmetic); the writer of the shipped file, {{src:scripts/fuse_sweep_m5.py|fuse_sweep_m5.py}}; the previous rule's writer, {{src:scripts/fuse_sweep.py|fuse_sweep.py}}. The shipped constants are <code>models/fusion_v2/constants.json</code> (not in the repository), the previous rule's <code>models/fusion_v1/constants.json</code>.</p>
<h2 id="params">The rule and where each piece is set</h2>
<ol>
<li><strong>Rank.</strong> Each logit's position among that detector's sorted inner out-of-fold logits, left-sided, as a fraction ({{src:src/hearsay/pipeline.py#L285|pipeline.py, lines 285–288}}). The references are stored in the constants file and validated as sorted, finite and non-empty.</li>
<li><strong>Blend.</strong> {{src:README.md#how-it-decides|0.6 × rank(M1b) + 0.2 × rank(handcrafted) + 0.2 × rank(M5)}}; the file's weights must be finite, positive, name fused columns other than Spectra, and sum to one ({{src:src/hearsay/pipeline.py#L167|pipeline.py, lines 167–185}}). The previous rule was a two-way blend with α = {{num:0.2|README.md#the-fusion-rule}} on the handcrafted column.</li>
<li><strong>The Spectra step.</strong> If Spectra's margin is below {{num:−3.0|scripts/fuse_sweep.py#L172}} and the base rank is above {{num:0.5|scripts/fuse_sweep.py#L172}}, the base is multiplied by {{num:0.5|scripts/fuse_sweep.py#L172}}; strict inequalities; a missing Spectra means no suppression; nothing is ever fitted on Spectra ({{src:src/hearsay/pipeline.py#L307|pipeline.py, lines 307–316}}).</li>
<li><strong>Platt map</strong> at the {{num:0.3|docs/reports/2026-09-26_worked-examples.md}} prior: a class-balanced logistic regression fit on the inner out-of-fold base scores, applied as sigmoid(a·base + b + the log prior odds) ({{src:src/hearsay/pipeline.py#L327|pipeline.py, line 327}}).</li>
<li><strong>The determinate map</strong> into [{{num:0.001|scripts/fuse_sweep.py#L159}}, 1], applied exactly once by the policy; gated files go below it.</li>
<li><strong>Imputation.</strong> A missing fused column is imputed at rank {{num:0.5|src/hearsay/pipeline.py#L300}}, the inner-fold median, and the fusion line names it ({{src:src/hearsay/pipeline.py#L299|pipeline.py, lines 299–300}}).</li>
</ol>
<p>A constants file that weights M5 must also record the M5 checkpoint's directory and hashes, and the runner refuses a checkpoint that does not match ({{src:src/hearsay/pipeline.py#L197|pipeline.py, lines 197–202}}).</p>
<h2 id="status">Status</h2>
<p>The shipped rule is <code>A3_w0.2_E</code>, ratified at 12:03 on Saturday and the runner's default since 12:35; the previous rule <code>E_on_A_alpha0.2</code> is loadable as the fallback. The two files fuse identically on their shared inputs (a test pins it), so the previous rule is exactly the shipped one with the M5 weight moved back to the probe.</p>
<h2 id="numbers">Numbers</h2>
<p>Shipped: inner {{num:0.135|README.md#results-at-a-glance}}, holdout {{num:0.0065|README.md#results-at-a-glance}}, In-the-Wild {{num:0.228|README.md#results-at-a-glance}} / {{num:0.239|README.md#numbers}}. Previous: {{num:0.140|README.md#results-at-a-glance}} / {{num:0.014|README.md#results-at-a-glance}} / {{num:0.260|README.md#results-at-a-glance}} / {{num:0.267|README.md#numbers}}. Between the two, Spearman {{num:0.974|README.md#the-fusion-rule}} on the test set and {{num:3 of 1,671|README.md#the-fusion-rule}} files cross {{num:0.5|README.md#the-fusion-rule}}. From exported logits the runner reproduces the submitted TSV to {{num:6.7e-16|README.md#score-a-directory-on-the-mac}}.</p>
<h2 id="limits">Known limits</h2>
<p>Not noise-robust: at 20 dB white noise the handcrafted column collapses and the rule's holdout cost rises from {{num:0.012|README.md#what-did-not-work}} to {{num:0.269|README.md#what-did-not-work}}, while the Spectra step never fires. Giving Spectra a full vote scores better on every labeled readout and was ruled out beforehand.</p>
<h2 id="tests">Tests that pin it</h2>
<p><code>tests/test_pipeline.py</code>: constants parse and validate, a file with mismatched weights is rejected, the rank rule is the sweep script's arithmetic including the left-sided boundary, the three-way blend is the M5 sweep's arithmetic, the Spectra step's boundaries are strict, the step can be off in the file, imputation, the previous file and its shipped twin fuse identically, the v2 file loads weights, references and the checkpoint identity and rejects bad files, the flip reverses determinate rows and keeps the block, the fusion line lists every weighted term; data-gated parity against the 09:14 candidate TSV.</p>
<h2 id="sources">Sources</h2>
<p>{{src:README.md#the-fusion-rule|README, "The fusion rule"}}; {{src:docs/reports/2026-09-26_fusion-sweep-predeclared.md|the sweep report}}; {{src:docs/consults/2026-09-26_fusion-strategy_RESPONSE.md|the fusion consult}}; {{src:docs/specs/2026-09-26_m4-fusion-v2-m5-scorer.md|the M5-scorer run spec}}.</p>
