<!-- {"title": "Handcrafted spectral and prosody features", "group": "Engineered detectors", "order": 40, "lead": "Two hundred and thirty-four engineered features of the spectrum and the prosody of a clip, fed to gradient-boosted trees that are evaluated in plain numpy at inference. Interpretable by construction: every sentence it writes names the three features that moved it and by how many standard deviations from real speech.", "sources": ["src/hearsay/handcrafted.py", "src/hearsay/hc_v4.py", "scripts/train_handcrafted.py", "docs/reports/2026-09-26_handcrafted-v4.md"]} -->
<h2 id="plain">In plain words</h2>
<p>The {{term:handcrafted detector}} is the one a person can argue with. It measures things with names, such as how much the cepstral coefficients change from frame to frame, how the pitch moves, whether the phase behaves like a vocoder's, and learns which of them separate real from synthetic. It is the {{term:spectral}} and the {{term:prosody}} techniques of the rubric in one detector. It is excellent on generators it has seen and blind to web-sourced fakes, which is why it has a fifth of the vote and not half.</p>
<h2 id="io">What goes in and comes out</h2>
<p>In: the band-matched, trimmed, test-length-cropped, RMS-normalized clip. Out: a probability from the trees (the exported logit is its logit), the feature values, and a sentence of the form <code>spectral/prosody features real-like (P=0.16): LFCC 16 frame-to-frame change 3.0 SD below real speech (toward synthetic); …</code>, the three largest contributions in standard deviations from the real-speech mean of the inner rows.</p>
<h2 id="where">Where it lives</h2>
<p>The 75 base features and the augmentation in {{src:src/hearsay/handcrafted.py|handcrafted.py}}; the six added families in {{src:src/hearsay/hc_v4.py|hc_v4.py}}; extraction and training in {{src:scripts/extract_handcrafted.py|extract_handcrafted.py}} and {{src:scripts/train_handcrafted.py|train_handcrafted.py}}; the detector wrapper in {{src:src/hearsay/detectors/handcrafted.py|detectors/handcrafted.py}} over the shared learned base; the numpy tree evaluator in {{src:src/hearsay/trees.py|trees.py}}.</p>
<h2 id="params">Parameters and where each is set</h2>
<ul>
<li><strong>The 75 base features:</strong> 64 spectral (high-band energy ratios at 4, 6 and 7 kHz, roll-offs, centroid, bandwidth, flatness, six-band spectral contrast, flux, 20 MFCC means and standard deviations) and 11 prosody (YIN pitch median, spread and slope, voiced fraction, energy dynamics, pauses, zero-crossing rate), on 32 ms frames every 10 ms ({{src:src/hearsay/handcrafted.py#L72|handcrafted.py, lines 72–140}}).</li>
<li><strong>The six added families</strong> ({{src:src/hearsay/hc_v4.py|hc_v4.py}}): LFCC (40 linear filters to 7 kHz, 20 coefficients, mean, standard deviation and delta), phase (group-delay spread per voiced frame, peak phase-versus-magnitude coherence), CQCC (a constant-Q transform from 65 Hz, 24 coefficients), the modulation spectrum of the loudness envelope in four bands, breath frames between speech, and cycle-level jitter and shimmer; {{num:234|README.md#the-eight-forensic-techniques}} columns in all.</li>
<li><strong>The per-column gate</strong> that admitted each family: a column is kept if it separates classes on grad_tts, pro_diff or ElevenLabs by a margin, does not mainly separate the two real corpora from each other, and survives a codec round-trip; the rule and the tables are in the report ({{src:docs/reports/2026-09-26_handcrafted-v4.md|the v4 report}}).</li>
<li><strong>Training:</strong> LightGBM ({{num:300|scripts/train_handcrafted.py#L70}} trees, 31 leaves, class-balanced) chosen over a logistic regression by inner out-of-fold minDCF, then refit on all inner rows; the bundle stores the dumped trees and the real-speech feature statistics, and the trainer asserts the numpy evaluator matches LightGBM ({{src:scripts/train_handcrafted.py#L64|train_handcrafted.py, lines 64–74}} and {{src:scripts/train_handcrafted.py#L255|lines 255–261}}).</li>
<li><strong>v5 augmentation, fit-only:</strong> codec round-trips and a random spectral tilt with a low-pass between {{num:4,500|src/hearsay/handcrafted.py#L153}} and {{num:7,000|src/hearsay/handcrafted.py#L153}} Hz, drawn per row; the augmented twins take their clean twin's fold, are excluded from their own validation fold and never enter a readout or the export, so every number is on clean rows ({{src:src/hearsay/handcrafted.py#L152|handcrafted.py, lines 152–197}}; {{src:scripts/train_handcrafted.py#L120|train_handcrafted.py, lines 120–123}}).</li>
<li><strong>Why numpy trees:</strong> LightGBM and PyTorch each ship an OpenMP runtime that crashes together on macOS, so nothing on the inference path imports LightGBM; the evaluator also gives per-feature path contributions for the sentence ({{src:src/hearsay/trees.py#L4|trees.py, lines 4–9}}).</li>
</ul>
<h2 id="status">Status</h2>
<p>Shipped as v5b at weight {{num:0.2|README.md#how-it-decides}}: the v4 columns with augmented twins, trained with augmentation and validated on clean rows only.</p>
<h2 id="numbers">Numbers</h2>
<p>v3 (75 features): inner {{num:0.614|README.md#numbers}}, holdout {{num:0.254|README.md#numbers}}. v4a ({{num:234|README.md#the-eight-forensic-techniques}} features): inner {{num:0.434|README.md#numbers}}, holdout {{num:0.170|README.md#numbers}}; pro_diff went from {{num:1.00|README.md#what-worked}} to {{num:0.32|README.md#what-worked}} out of fold. v5b: inner {{num:0.469|README.md#numbers}}, holdout {{num:0.137|README.md#numbers}} (EER {{num:3.1%|README.md#numbers}}), In-the-Wild false alarms {{num:0.40%|README.md#numbers}}, test share above {{num:0.5|README.md#numbers}} {{num:45.1%|README.md#numbers}}; holdout-real false alarms fell from {{num:9.1%|README.md#what-worked}} to {{num:6.3%|README.md#what-worked}}. Trees beat the linear model on the same features, holdout {{num:0.374|README.md#what-worked}} against {{num:0.661|README.md#what-worked}}.</p>
<h2 id="limits">Known limits</h2>
<p>In-the-Wild minDCF {{num:1.00|README.md#what-did-not-work}}: it does not transfer to web-sourced fakes. Even band-matched, the columns tell training from test audio at {{term:AUC}} {{num:0.99|README.md#what-did-not-work}}, and pruning the shifted columns made it worse. grad_tts is invisible to it when held out. At 20 dB white noise it loses almost all discrimination (AUC {{num:0.998|README.md#what-did-not-work}} → {{num:0.64|README.md#what-did-not-work}}), the shipped rule's weak spot.</p>
<h2 id="tests">Tests that pin it</h2>
<p><code>tests/test_handcrafted_detector.py</code> (contract, direction, the sentence names features and direction, memoization, a missing model is an error, the bundle's families are recomputed at inference), <code>test_hc_v4.py</code> (key sets, offset invariance, phase coherence, LFCC tilt, modulation sums, jitter), <code>test_hc_augment.py</code> (tilt darkens or brightens, reproducible draws, augmentation off by default), <code>test_trees.py</code> (matches LightGBM, contributions sum to the raw score, agrees with SHAP on top features, NaN handling, categorical splits rejected, no LightGBM import).</p>
<h2 id="sources">Sources</h2>
<p>{{src:docs/reports/2026-09-26_cpu-detectors.md|The CPU detectors report}}; {{src:docs/reports/2026-09-26_handcrafted-v4.md|the v4 and v5 report}}; {{src:docs/handoffs/2026-09-26_feature-engineering-map.md|the feature-engineering map}}; {{src:docs/architecture.md#7-engineered-detectors|Architecture §7}}.</p>
