<!-- {"title": "The M5 head on XLS-R", "group": "Deep detectors", "order": 32, "lead": "A trained head on the first twelve layers of XLS-R: learned layer weights, attentive statistics pooling and a linear output, trained on rented A100s with heavy class-blind augmentation. It failed its gate as a replacement for the probe and ships as a fifth of the fusion vote, because it errs on different files.", "sources": ["src/hearsay/m5_model.py", "src/hearsay/m5_data.py", "src/hearsay/augment.py", "docs/reports/2026-09-26_m5-xlsr-finetune.md"]} -->
<h2 id="plain">In plain words</h2>
<p>The plan for {{term:M5}} was to fine-tune XLS-R and beat the frozen probe. Fine-tuning the kept layers fit the seen generators and transferred worse to the unseen one, so the shipped arm keeps the backbone frozen and trains only a small head over the hidden states. On its own that head lost to the probe on the holdout, on LibriSpeech real speech and on short clips, and won only on In-the-Wild false alarms. The pre-declared M5 sweep then showed that as a minority vote beside the probe and the handcrafted model it improves every readout, which is the role it ships in.</p>
<h2 id="io">What goes in and comes out</h2>
<p>In: trimmed, band-limited, capped and normalized audio (the deploy transform). Out: one logit, high for synthetic, mapped to a probability for the sentence "XLS-R fine-tuned head (M5, 12 layers, attentive pooling): logit +x.xx (synthetic-like, P=0.xx)". Export column <code>m5_xlsr_ft</code>.</p>
<h2 id="where">Where it lives</h2>
<p>Model in {{src:src/hearsay/m5_model.py|m5_model.py}}; data, folds and the deploy transform in {{src:src/hearsay/m5_data.py|m5_data.py}}; augmentation in {{src:src/hearsay/augment.py|augment.py}}; the bundle in {{src:src/hearsay/m5_bundle.py|m5_bundle.py}}; trainer, scorer and assembler in <code>scripts/m5_*.py</code>; the vast.ai launch and reaper scripts under <code>scripts/cloud/</code>; the runner's path in {{src:src/hearsay/pipeline.py#L485|pipeline.py, lines 485–495}}.</p>
<h2 id="params">Parameters and where each is set</h2>
<ul>
<li><strong>Architecture:</strong> 12 kept layers, a softmax-weighted sum over the hidden states, masked attentive statistics pooling with a bottleneck of {{num:128|src/hearsay/m5_model.py#L27}} (mean and standard deviation concatenated), a linear head ({{src:src/hearsay/m5_model.py#L21|m5_model.py, lines 21–110}}). The CNN feature encoder is always frozen; with <code>train_top = 0</code> every backbone parameter is frozen, which is the shipped arm.</li>
<li><strong>Training recipe</strong> (defaults in <code>M5Config</code>): layer-wise learning-rate decay {{num:0.85|src/hearsay/m5_model.py#L29}}, weight decay {{num:0.01|src/hearsay/m5_model.py#L31}}, warmup {{num:0.08|src/hearsay/m5_model.py#L32}} then cosine, label smoothing {{num:0.05|src/hearsay/m5_model.py#L34}}, gradient clip {{num:1.0|src/hearsay/m5_model.py#L36}}, batches of 32 crops, bf16 on the A100; {{num:3,000|docs/reports/2026-09-26_m5-xlsr-finetune.md}} steps for the full model. A direction tripwire aborts a fold model whose validation AUC is not above chance.</li>
<li><strong>Batch mix</strong> ({{src:src/hearsay/m5_model.py#L43|m5_model.py, lines 43–47}}): real speech LJ {{num:0.25|src/hearsay/m5_model.py#L45}}, LibriSpeech {{num:0.35|src/hearsay/m5_model.py#L45}}, ASVspoof 2019 {{num:0.40|src/hearsay/m5_model.py#L45}}; spoof DiffSSD {{num:0.78|src/hearsay/m5_model.py#L45}}, MLAAD {{num:0.12|src/hearsay/m5_model.py#L45}}, ASVspoof {{num:0.10|src/hearsay/m5_model.py#L45}}; label-balanced batches, half and half.</li>
<li><strong>Augmentation, class-blind:</strong> applied with probability {{num:0.65|src/hearsay/m5_model.py#L39}}, one op with probability {{num:0.6|src/hearsay/augment.py#L127}} else two, RawBoost appended with probability {{num:0.25|src/hearsay/m5_model.py#L40}}: white or pink noise at 5–30 dB SNR, telephony band-limits at {{num:3,400|src/hearsay/augment.py#L27}} or {{num:4,000|src/hearsay/augment.py#L27}} Hz, reverb with RT60 {{num:0.2|src/hearsay/augment.py#L28}}–{{num:0.8|src/hearsay/augment.py#L28}} s, gain and clipping, notch-and-nonlinearity, codec round-trips (MP3, Opus, AAC, AMR-NB, μ-law) on a share of rows and every holdout row; then the deterministic band match last ({{src:src/hearsay/augment.py#L25|augment.py, lines 25–163}}).</li>
<li><strong>Fold discipline:</strong> the fold files are hash-pinned; a fold model never sees its own fold, a holdout row, or the generator families that validate on that fold (OpenVoice, XTTS, ElevenLabs); In-the-Wild paths are refused ({{src:src/hearsay/m5_data.py#L28|m5_data.py, lines 28–40}} and {{src:src/hearsay/m5_data.py#L166|lines 166–179}}).</li>
<li><strong>Checkpoint pinning:</strong> the saved model carries hashes of its config, backbone and head; the loader and the runner refuse a mismatch, and a constants file that weights M5 must record those hashes ({{src:src/hearsay/m5_model.py#L173|m5_model.py, lines 173–223}}; {{src:src/hearsay/pipeline.py#L351|pipeline.py, lines 351–364}}).</li>
</ul>
<h2 id="status">Status</h2>
<p>Gate not passed as a replacement; shipped at weight {{num:0.2|README.md#how-it-decides}} since the noon switch. Twelve A100 instances were rented (six never booted), {{num:$5.42|README.md#what-did-not-work}} in total; the checkpoint is also on the Hugging Face Hub, private.</p>
<h2 id="numbers">Numbers</h2>
<p>Alone: inner {{num:0.302|README.md#numbers}}, holdout {{num:0.363|README.md#numbers}} against {{num:0.159|README.md#what-did-not-work}} for the probe, In-the-Wild false alarms {{num:0.45%|README.md#numbers}} against {{num:0.7%|README.md#what-did-not-work}}, clips under 4 s at {{num:0.60|README.md#what-did-not-work}}; the fine-tuned arms scored {{num:0.38–0.41|README.md#what-did-not-work}} on the ElevenLabs fold against {{num:0.31|README.md#what-did-not-work}} frozen. In the fusion: holdout {{num:0.014|README.md#what-worked}} → {{num:0.0065|README.md#what-worked}}, In-the-Wild {{num:0.260|README.md#what-worked}} → {{num:0.228|README.md#what-worked}}. Live CPU against the A100 export, the logit differs by at most {{num:0.035|README.md#score-a-directory-on-the-mac}} (median {{num:7.0e-4|README.md#score-a-directory-on-the-mac}}).</p>
<h2 id="limits">Known limits</h2>
<p>The final encoder LayerNorm and the mask embedding were unintentionally trainable in the shipped run (a few thousand parameters); fixed afterwards and pinned by a test. The M5 addendum's first In-the-Wild run scored whole clips instead of the shared crops and was repeated crop-fair; both are reported. On MLAAD its miss rate is the in-sample one.</p>
<h2 id="tests">Tests that pin it</h2>
<p><code>tests/test_m5_model.py</code> (frozen and trainable sets with a counterfactual, padding invariance, direction, determinism, save and load hash refusal, layer-wise decay and no-decay rules, layer weights sum to one), <code>test_m5_bundle.py</code>, <code>test_m5_manifest.py</code> (no holdout row in any training set, the fold-file hashes, shortcut AUCs), <code>test_m5_crops.py</code>, <code>test_m5_codecs.py</code>, <code>test_m5_scores.py</code>, <code>test_m5_train.py</code> (smoke runs, resume, the tree-hash refusal), <code>test_augment.py</code>, <code>test_cloud_scripts.py</code>; in <code>test_pipeline.py</code> the identity gate and the live logit's agreement with the scorer.</p>
<h2 id="sources">Sources</h2>
<p>{{src:docs/reports/2026-09-26_m5-xlsr-finetune.md|The M5 report}}; {{src:docs/reports/2026-09-26_fusion-sweep-predeclared.md#addendum-m5-candidates-pre-declared-before-any-run-sat-0835-requested-by-nathan-via-the-oversight-chat|the M5 addendum}}; {{src:docs/consults/2026-09-26_m5-extra-data-finetune_RESPONSE.md|the extra-data consult}}; {{src:docs/reports/cloud-expense-ledger.md|the expense ledger}}.</p>
