<!-- {"title": "The runner and its routing rules", "group": "Orchestration", "order": 20, "lead": "One script takes a directory of audio and produces the TSV, one explanation JSON per file, timings and a resumable cache. Inside it, a short list of fixed rules over measured facts decides what each detector's result may do. That list is the orchestrator.", "sources": ["src/hearsay/pipeline.py", "scripts/run_pipeline.py", "docs/reports/2026-09-26_runner-docker.md"]} -->
<h2 id="plain">In plain words</h2>
<p>Orchestration here is not a learned router and not a language model. Every detector runs on every file (the whole test set is about 95 minutes of audio, so compute was never the constraint). What the rules decide is what each result is <em>allowed to do</em> to the score, and every decision is written to the file's routing log so it can be checked afterwards. The rules are on the <a href="../how-it-decides.html#router">How it decides</a> page as a diagram; this page is the reference.</p>
<h2 id="io">What goes in and comes out</h2>
<p>In: a directory of audio files and, optionally, the sponsor's template TSV that fixes the row order. Out, under the output directory: the TSV (never overwritten; a clash gets a timestamp suffix), a <code>results/</code> folder with one JSON per file, a resumable <code>results.jsonl</code>, <code>timings.csv</code>, a sidecar CSV of the per-detector values, <code>run_meta.json</code>, and the preflight outputs.</p>
<h2 id="where">Where it lives</h2>
<p>{{src:src/hearsay/pipeline.py|src/hearsay/pipeline.py}}: the constants, the <code>Models</code> loader, <code>analyze_clip</code>, <code>routing_log</code>, <code>fusion_line</code>, <code>final_score</code> and <code>refuse</code>. {{src:scripts/run_pipeline.py|scripts/run_pipeline.py}}: the command line, the template reader, the cache, the preflight, the TSV writer and the exit codes.</p>
<h2 id="params">The rules and where each is set</h2>
<ul>
<li><strong>Container → compression.</strong> The container detector's facts set how compression forensics is reported: a lossy header gets "compression forensics apply (evidence)"; a PCM file written by FFmpeg (every test file) gets "run for evidence, not score" ({{src:src/hearsay/pipeline.py#L605|pipeline.py, lines 605–615}}). Either way the compression score never enters fusion.</li>
<li><strong>Bandwidth.</strong> The compression detector's effective bandwidth is reported against the band match: at or below {{num:7,250|src/hearsay/pipeline.py#L618}} Hz, or above it ({{src:src/hearsay/pipeline.py#L616|pipeline.py, lines 616–619}}). This is the one bandwidth threshold in the router; the {{num:7,500|README.md#orchestration-what-routing-changes}} Hz figure in the reports is an inventory reading, not a rule.</li>
<li><strong>Speech gate → abstention.</strong> A file the gate rejects skips fusion and goes to the pinned block; a gate <em>error</em> does not gate the file ({{src:src/hearsay/pipeline.py#L636|pipeline.py, lines 636–645}}). See <a href="speech-gate-policy.html">the gate and the default-answer policy</a>.</li>
<li><strong>Spectra → suppression only.</strong> If Spectra's margin is below the constants file's threshold and the fused rank is above its threshold, the rank is halved; if Spectra is missing, nothing is suppressed ({{src:src/hearsay/pipeline.py#L307|pipeline.py, lines 307–316}}). The thresholds themselves are in <a href="fusion-rule.html">the fusion rule</a>.</li>
<li><strong>Evidence-only detectors</strong> (ENF, splice, speaker drift, compression) are written to the log and the evidence list and never touch the score ({{src:src/hearsay/pipeline.py#L620|pipeline.py, lines 620–635}}).</li>
<li><strong>Imputation.</strong> A fused detector that errors on a file has its column imputed at the inner-fold centre (rank {{num:0.5|src/hearsay/pipeline.py#L299}}), and the fusion line names it ({{src:src/hearsay/pipeline.py#L299|pipeline.py, lines 299–300}}). A deep scorer that raises or returns a non-finite value becomes an error entry; the row is kept.</li>
<li><strong>Decode failure.</strong> No detector runs; the file is flagged and lands below the block ({{src:src/hearsay/pipeline.py#L603|pipeline.py, lines 603–604}}).</li>
</ul>
<h3 id="cli">Command line</h3>
<p><code>--in</code>, <code>--out</code>, <code>--template</code>, <code>--team</code> (the default is not our team name; the deliverable passes <code>CrossExam</code>), <code>--fusion</code> (default: the shipped constants file since the 12:35 switch), <code>--rule</code>, <code>--policy</code>, <code>--flip</code> (writes the pre-flipped twin through the same map), <code>--detectors</code> (cannot narrow the set the constants file needs), <code>--m5</code>, <code>--threads</code> (capped at {{num:6|src/hearsay/pipeline.py#L102}}), <code>--require-offline</code>, <code>--no-truncate</code>, <code>--fresh</code>, <code>--compare-tsv</code>, <code>--preflight</code>. Environment variables mirror the main flags ({{src:scripts/run_pipeline.py#L98|run_pipeline.py, lines 98–144}}).</p>
<h3 id="preflight">Preflight and cache</h3>
<p>Before scoring, four seconds of silence and a three-note chord are scored twice through the whole pipeline: both probabilities must be finite and agree, every scorer must be ok, neither clip may pass the gate, and both must land below the block ({{src:scripts/run_pipeline.py#L318|run_pipeline.py, lines 318–354}}). The cache header records the models, the constants file's hash and the scorer set; a mismatch moves the old cache aside; rule, policy and polarity are not part of the identity, so cached logits are re-fused in a fraction of a second ({{src:scripts/run_pipeline.py#L247|run_pipeline.py, lines 247–303}}).</p>
<h2 id="status">Status</h2>
<p>Built; the default constants file is the shipped rule since the 12:35 switch on Saturday. Live from audio on all {{num:1,671|README.md#score-a-directory-on-the-mac}} files it reproduces the submitted TSV with Spearman {{num:1.000000|README.md#score-a-directory-on-the-mac}} and a maximum difference of {{num:9.3e-4|README.md#score-a-directory-on-the-mac}}.</p>
<h2 id="numbers">Numbers</h2>
<p>Speed with M5 loaded: {{num:1.34 s|README.md#score-a-directory-on-the-mac}} per file; peak memory {{num:4.0 GB|README.md#score-a-directory-on-the-mac}}. The router-on versus router-off ablation is on <a href="../how-it-decides.html#router-measured">How it decides</a>.</p>
<h2 id="limits">Known limits</h2>
<p>The verdict field compares the pre-map fused probability with {{num:0.5|src/hearsay/pipeline.py#L652}} and ignores <code>--flip</code>; it is a label for the report, not the ranking the metric scores. A comment in the runner and the Docker build script still name the previous default; the code's default is the shipped file.</p>
<h2 id="tests">Tests that pin it</h2>
<p><code>tests/test_pipeline.py</code>: response shape, the map applied exactly once, the routing log reads the detector features (order and wording), lossy/seams/hum/drift wording, the default answer applied when there is no speech, a gate error does not gate, a failed fused detector is imputed and logged, a decode failure sits below the block, re-fusing switches rule, policy and polarity without models, scorers come from the constants file, the cache identity gates the resume and tolerates a torn line, the template is read in order and missing files are flagged, exit code 4 when a weighted scorer fails, the preflight refuses a failing scorer, <code>--require-offline</code> refuses without the environment.</p>
<h2 id="sources">Sources</h2>
<p>{{src:README.md#orchestration-what-routing-changes|README, "Orchestration"}}; {{src:docs/reports/2026-09-26_runner-docker.md|the runner report}}; {{src:docs/reports/2026-09-26_worked-examples.md|the worked examples}}; {{src:docs/specs/2026-09-26_m4-fusion-v2-m5-scorer.md|the M5-scorer run spec}}.</p>
