<!-- {"title": "Segment preparation and band match", "group": "Ingest", "order": 12, "lead": "Training and test audio must look the same to a detector, or the detector learns the difference instead of the voice. This stage low-passes every clip at the test set's roll-off, trims silence, crops training rows to test-like lengths, caps the length and normalizes the level.", "sources": ["src/hearsay/embed.py", "src/hearsay/handcrafted.py", "docs/reports/2026-09-26_cpu-detectors.md"]} -->
<h2 id="plain">In plain words</h2>
<p>The test files carry a wall in their spectrum at about {{num:7.2 kHz|README.md#what-worked}} that no training corpus has, and they are shorter, louder and start faster than the training clips. Each of those differences is a {{term:shortcut}} a model would happily learn. So every clip, train and test, deep path and engineered path, goes through the same preparation before a detector sees it. The {{term:band match}} alone took the handcrafted detector from calling {{num:90%|README.md#what-worked}} of the test set synthetic to {{num:42%|README.md#what-worked}}.</p>
<h2 id="io">What goes in and comes out</h2>
<p>In: a 16 kHz mono array, and for training rows a crop length drawn from the test set's duration distribution and a seed. Out: the prepared segment. Training rows are cropped; test rows are never cropped, padded or tiled.</p>
<h2 id="where">Where it lives</h2>
<p><code>prepare_segment</code>, <code>normalize_windows</code>, <code>embed_segment</code> and <code>test_duration_sampler</code> in {{src:src/hearsay/embed.py|embed.py}}; <code>band_limit</code> and <code>_crop</code> in {{src:src/hearsay/handcrafted.py|handcrafted.py}}. Spectra-AASIST's input path is exactly <code>prepare_segment</code>; M5 uses the same steps in a slightly different order (trim, then band-limit) that differs by at most one 20 ms frame.</p>
<h2 id="params">Parameters and where each is set</h2>
<ul>
<li><strong>The band-match filter:</strong> a Kaiser FIR low-pass, cutoff {{num:7,250|src/hearsay/handcrafted.py#L39}} Hz, transition width {{num:600|src/hearsay/handcrafted.py#L39}} Hz, {{num:45|src/hearsay/handcrafted.py#L39}} dB attenuation, 71 taps, applied zero-delay by FFT convolution and cached once per process ({{src:src/hearsay/handcrafted.py#L39|handcrafted.py, lines 39–52}}). The rationale in the comment block: {{num:1,602|src/hearsay/handcrafted.py#L34}} of the {{num:1,671|README.md#numbers}} test files carry the roll-off.</li>
<li><strong>Order in <code>prepare_segment</code>:</strong> band-limit (unless told the caller already did), silence trim, a seeded random crop for training rows only, then a cap at {{num:8.0|src/hearsay/embed.py#L23}} s ({{src:src/hearsay/embed.py#L80|embed.py, lines 80–102}}).</li>
<li><strong>Normalization:</strong> the deep path normalizes each input to zero mean and unit variance ({{src:src/hearsay/embed.py#L38|embed.py, lines 38–43}}); the engineered path normalizes to an RMS of {{num:0.1|src/hearsay/handcrafted.py#L69}} ({{src:src/hearsay/handcrafted.py#L55|handcrafted.py, lines 55–69}}). Level is therefore never a feature.</li>
<li><strong>Crop lengths</strong> are drawn from the test set's own durations ({{src:src/hearsay/embed.py#L71|embed.py, lines 71–77}}): the test clips run {{num:3.0|docs/STATUS.md#data}}–{{num:13.6|docs/STATUS.md#data}} s with a median of {{num:3.4|docs/STATUS.md#data}} s, and the training clips 5–9 s. One draw per manifest row, offset seeded by row, so an extraction is reproducible.</li>
</ul>
<h2 id="status">Status</h2>
<p>Built. The deep path gained the band match at about 04:20 on Saturday; every deep number on this site postdates it (the earlier v2 probe numbers are marked as pre-band-match in the README's tables).</p>
<h2 id="numbers">Numbers</h2>
<p>Length parity alone was worth {{num:0.05|README.md#what-worked}} for the handcrafted detector ({{num:0.709|README.md#what-worked}} → {{num:0.661|README.md#what-worked}}). Band matching and real-speaker diversity together took the probe's holdout from {{num:0.159|README.md#what-worked}} to {{num:0.072|README.md#what-worked}}.</p>
<h2 id="limits">Known limits</h2>
<p>The wall is matched, not explained: the codec hunt found no MP3 or AAC setting that reproduces it better than this filter, so the test set's low-pass is treated as a resampler's anti-alias filter. Even band-matched, the test recordings keep a darker spectral envelope that the handcrafted features can see (the test-domain offset on <a href="../what-worked.html#did-not-work">What did not work</a>).</p>
<h2 id="tests">Tests that pin it</h2>
<p><code>tests/test_audio_and_submission.py</code>: no tiling and deterministic crops, the sampler's draws match the test range, the band match pushes energy above the cutoff below one part in ten thousand while leaving the 1 kHz passband alone, normalization removes level and offset. <code>tests/test_spectra.py</code> pins that Spectra's input path is <code>prepare_segment</code>; <code>tests/test_m5_crops.py</code> pins M5's deploy path; <code>tests/test_compression_detector.py</code> pins the effective bandwidth after the filter.</p>
<h2 id="sources">Sources</h2>
<p>{{src:docs/reports/2026-09-26_cpu-detectors.md|The CPU detectors report, "Trap 2"}}; {{src:docs/architecture.md#4-invariants-the-rules-the-code-enforces|Architecture, invariant 2}}; {{src:docs/architecture.md#11-shortcut-ledger|the shortcut ledger}}.</p>
