<!-- {"title": "Spectra-AASIST (M3)", "group": "Deep detectors", "order": 31, "lead": "An off-the-shelf anti-spoofing model run with no training through the same input path as everything else. The strongest detector on every set we hold, and the one we trust least, because its training data is undisclosed. It may only lower a score.", "sources": ["src/hearsay/spectra.py", "scripts/score_spectra.py", "docs/reports/2026-09-26_m3-spectra.md"]} -->
<h2 id="plain">In plain words</h2>
<p>A published model with its own copy of XLS-R and a graph-attention back end, built for exactly this task. It separates our training rows perfectly, which is either brilliance or memory: its model card names no training set, and LJ Speech, LibriSpeech and DiffSSD are all public. So it does not vote. When it is confident a voice is real and the other detectors lean synthetic, it halves the fused rank; if it is wrong that way the cost is a miss, never the expensive false alarm. The leakage probes later supported that role.</p>
<h2 id="io">What goes in and comes out</h2>
<p>In: the prepared segment, cut into windows of {{num:64,600|src/hearsay/spectra.py#L40}} samples (about 4 s) at half-window hops, at most 16 windows, with pre-emphasis; short clips zero-padded to one window. Out: the average over windows of the spoof logit minus the bona fide logit, a margin that rises with synthetic likelihood ({{src:src/hearsay/spectra.py#L135|spectra.py, line 135}}). The evidence sentence: "Spectra-AASIST: spoof-minus-bonafide margin +x.xx (synthetic-like, P=0.xx)".</p>
<h2 id="where">Where it lives</h2>
<p>{{src:src/hearsay/spectra.py|spectra.py}} (loader with the hub id redirected to the local weights, input preparation, padding modes, window scoring, the direction check); {{src:scripts/score_spectra.py|score_spectra.py}} (the export with failure and direction gates); {{src:scripts/spectra_direction.py|spectra_direction.py}}; the runner's path in {{src:src/hearsay/pipeline.py#L477|pipeline.py, lines 477–483}}.</p>
<h2 id="params">Parameters and where each is set</h2>
<ul>
<li>Output index 0 is spoof and 1 is bona fide; the exported logit is the raw margin, nothing is fitted on it ({{src:src/hearsay/spectra.py#L3|spectra.py, lines 3–11}}).</li>
<li>Inputs above {{num:128,000|src/hearsay/spectra.py#L43}} samples are refused (the model's positional table); the runner uses zero-padding and at most 16 windows ({{src:src/hearsay/pipeline.py#L98|pipeline.py, lines 98–99}}).</li>
<li>The short-clip padding mode was chosen by a pilot on inner rows: zero-pad won over repeat-tiling and whole-clip; a peak-normalization arm was tried and rejected because it cost {{num:0.033|README.md#what-did-not-work}} on real speech without removing the level correlation it targeted.</li>
<li>The suppression step it feeds: margin below {{num:−3.0|scripts/fuse_sweep.py#L172}} and fused rank above {{num:0.5|scripts/fuse_sweep.py#L172}} halves the rank; the constants are in <a href="fusion-rule.html">the fusion rule</a>.</li>
</ul>
<h2 id="status">Status</h2>
<p>Shipped as a suppressor with weight zero in the blend. Its "fused" role label in the runner's code is stale; the reports and this site say suppressor.</p>
<h2 id="numbers">Numbers</h2>
<p>All possibly in-sample: inner {{num:0.0045|README.md#numbers}}, holdout {{num:0.012|README.md#numbers}} (EER {{num:0.16%|README.md#numbers}}), In-the-Wild {{num:0.065|README.md#numbers}} with {{num:0.0%|README.md#numbers}} false alarms (its authors evaluated on that set), test share above {{num:0.5|README.md#numbers}} {{num:29.3%|README.md#numbers}}. As a suppressor it moved In-the-Wild from {{num:0.322|README.md#what-worked}} to {{num:0.260|README.md#what-worked}} in the first sweep. Probes: the most perturbation-stable detector (mean |ΔAUC| {{num:0.0008|README.md#what-did-not-work}} against {{num:0.0041|README.md#what-did-not-work}} for the probe), the lowest miss rate on {{num:143|README.md#what-did-not-work}} unseen generators ({{num:14.9%|README.md#what-did-not-work}}), and a step that never raised the fused holdout cost. Giving it a full vote would score better on every labeled readout (holdout {{num:0.0045|README.md#orchestration-what-routing-changes}}), which we ruled out beforehand.</p>
<h2 id="limits">Known limits</h2>
<p>Under 20 dB noise its own score holds ({{num:0.116|README.md#what-did-not-work}}) but the noise pushes it out of its "strongly real" region, so the step never fires and cannot help. It disagrees with the probe on {{num:154|docs/STATUS.md#where-things-stand}} test files. Its licence is unclear: the repository header says Apache-2.0, the model card says MIT.</p>
<h2 id="tests">Tests that pin it</h2>
<p><code>tests/test_spectra.py</code>, 39 hermetic tests with a fake torch: the input path equals <code>prepare_segment</code>, the band match drops a tone above the cutoff by more than 40 dB, test rows are not cropped and are capped, the crop plan reproduces the shared recipe with pinned seed-0 draws, padding modes and pad counts, the forward guard, long clips are identical across modes, pre-emphasis is applied, degenerate inputs stay finite, the direction contract, the window mean, the max-windows cap reaches the model, non-finite output is a failure, the script's export, gates and readouts; plus one weights-gated real run.</p>
<h2 id="sources">Sources</h2>
<p>{{src:docs/reports/2026-09-26_m3-spectra.md|The M3 report}}; {{src:docs/reports/2026-09-26_channel-robustness.md#e-is-m3-memorising-and-what-does-its-suppression-step-cost|the leakage probes}}; {{src:docs/architecture.md#63-spectra-aasist-m3|Architecture §6.3}}; {{src:docs/specs/2026-09-26_m3-spectra-aasist.md|the run spec}}.</p>
