<!-- {"title": "The XLS-R probe (M1, M1b)", "group": "Deep detectors", "order": 30, "lead": "A frozen self-supervised speech model, one of its middle layers averaged over time, and a small logistic classifier on top. It is the primary detector, with the largest weight in the fusion, and the one every other rung was measured against.", "sources": ["src/hearsay/embed.py", "src/hearsay/probe.py", "README.md"]} -->
<h2 id="plain">In plain words</h2>
<p>{{term:XLS-R}} was trained to predict masked speech in many languages, never to spot fakes; but its middle layers encode fine acoustic detail, and a vocoder leaves traces there that a voice does not. We read one layer, average it over the clip, and fit a logistic regression that says how far the clip sits toward synthetic. "Probe" because the big model is never changed: only the {{num:1,024|docs/architecture.md#61-depth-at-a-glance}} weights of the classifier are learned. M1b is the same probe with 40 more real speakers in the training folds.</p>
<h2 id="io">What goes in and comes out</h2>
<p>In: the prepared segment (band-matched, trimmed, normalized). Out: a calibrated {{term:LLR}}, positive for synthetic-like, mapped through a {{term:Platt map}}; the evidence sentence reads "XLS-R layer-7 probe: calibrated log-likelihood ratio +x.xx (synthetic-like, P=0.xx)". Its export column is <code>m1b_v3</code>.</p>
<h2 id="where">Where it lives</h2>
<p>Embedding in {{src:src/hearsay/embed.py|embed.py}} (<code>embed_segment</code>: one forward pass over the whole segment, the time-mean of every hidden state kept, so the layer choice happens at probe time); the classifier in {{src:src/hearsay/probe.py|probe.py}}; extraction, training and export in {{src:scripts/extract_embeddings.py|extract_embeddings.py}}, {{src:scripts/train_probe.py|train_probe.py}} and {{src:scripts/export_probe_scores.py|export_probe_scores.py}}; the runner's path in {{src:src/hearsay/pipeline.py#L466|pipeline.py, lines 466–475}}.</p>
<h2 id="params">Parameters and where each is set</h2>
<ul>
<li><strong>Layer 7</strong>, chosen by inner cross-validation: {{num:0.257|README.md#deep-detectors}} out of fold, with layers 6 and 8 close and layers 20 and above at {{num:0.40–0.43|README.md#deep-detectors}} ({{src:README.md#deep-detectors|README}}). The runner truncates the backbone after that layer so the hidden state stays bit-identical and about two thirds of the compute is skipped ({{src:src/hearsay/pipeline.py#L380|pipeline.py, lines 380–389}}).</li>
<li><strong>The classifier:</strong> a standard scaler then a class-balanced logistic regression with C = 1 and at most {{num:3,000|src/hearsay/probe.py#L45}} iterations, fit fold-locally ({{src:src/hearsay/probe.py#L43|probe.py, lines 43–47}}); the layer with the lowest out-of-fold minDCF wins, ties by EER; a Platt map is fit on the winning layer's out-of-fold scores, then the probe is refit on all inner rows ({{src:scripts/train_probe.py#L70|train_probe.py, lines 70–79}}).</li>
<li><strong>Embedding stored in float16</strong> for the runner; the parity cost is a maximum logit difference of {{num:5.3e-4|src/hearsay/pipeline.py#L101}} on 50 files ({{src:src/hearsay/pipeline.py#L100|pipeline.py, lines 100–101}}).</li>
<li><strong>M1b's extra rows:</strong> {{num:5,128|docs/architecture.md#62-xls-r-backbone-with-the-m1-probe-and-the-m5-head}} ASVspoof 2019 real clips from 40 VCTK speakers and {{num:2,520|docs/architecture.md#62-xls-r-backbone-with-the-m1-probe-and-the-m5-head}} spoof anchors, inner folds only ({{src:scripts/extend_folds.py|extend_folds.py}}).</li>
<li><strong>Segment mode:</strong> the earlier fixed 4-second windows tiled short test clips and put a seam only in test data; the shipped probe embeds each clip at its own length ({{src:src/hearsay/embed.py#L63|embed.py, lines 63–68}}).</li>
</ul>
<h2 id="status">Status</h2>
<p>Shipped as the {{num:0.6|README.md#how-it-decides}} weight of the fusion. Three versions were trained: v2 before the band match, v3 band-matched, M1b v3 with the extra speakers.</p>
<h2 id="numbers">Numbers</h2>
<p>M1b v3: inner {{num:0.301|README.md#numbers}}, holdout {{num:0.072|README.md#numbers}} (EER {{num:1.4%|README.md#numbers}}), In-the-Wild {{num:0.342|README.md#numbers}} with false alarms {{num:0.8%|README.md#numbers}}, test share above {{num:0.5|README.md#numbers}} {{num:26.8%|README.md#numbers}}. Band matching then the extra speakers took the holdout from {{num:0.159|README.md#what-worked}} to {{num:0.072|README.md#what-worked}}; before band matching the same speakers made In-the-Wild worse ({{num:0.374|README.md#what-worked}} → {{num:0.405|README.md#what-worked}}). Under 20 dB white noise its holdout cost rises from {{num:0.056|README.md#what-did-not-work}} to {{num:0.271|README.md#what-did-not-work}}.</p>
<h2 id="limits">Known limits</h2>
<p>Like every probe we trained it sits at {{num:0.34–0.41|README.md#what-did-not-work}} on In-the-Wild against {{num:0.07–0.16|README.md#what-did-not-work}} on the holdout: channel robustness is the gap. A runner comment about the probe's segment flag is stale; the runner uses segment mode regardless.</p>
<h2 id="tests">Tests that pin it</h2>
<p><code>tests/test_pipeline.py</code>: truncation keeps the probe layer identical on a tiny model (and, weights-gated, on the real one), M1-only mode is the probe arithmetic. <code>tests/test_audio_and_submission.py</code>: the segment path never tiles and crops deterministically, normalization removes level, the band match, the bulk extraction path matches the clip path (weights-gated).</p>
<h2 id="sources">Sources</h2>
<p>{{src:README.md#deep-detectors|README, "Deep detectors"}}; {{src:docs/reports/2026-09-26_m1b-asv19-bonafide.md|the M1b report}}; {{src:docs/reports/2026-09-25_m1-public-probe.md|the public-probe shakedown}}; {{src:docs/architecture.md#62-xls-r-backbone-with-the-m1-probe-and-the-m5-head|Architecture §6.2}}.</p>
